In [109]:
import pandas as pd 
import os 
import numpy as np

In [110]:
#df = pd.read_csv('Resources/missing_grades.csv')
df = pd.read_csv('Resources/students_complete.csv')
df.head()

,Student ID,student_name,gender,grade,school_name,reading_score,math_score
0,0,Paul Bradley,M,9th,Huang High School,66,79
1,1,Victor Smith,M,12th,Huang High School,94,61
2,2,Kevin Rodriguez,M,12th,Huang High School,90,60
3,3,Dr. Richard Scott,M,12th,Huang High School,67,58
4,4,Bonnie Ray,F,9th,Huang High School,97,84

In [111]:
df.count()

Student ID       39170
student_name     39170
gender           39170
grade            39170
school_name      39170
reading_score    39170
math_score       39170
dtype: int64

In [112]:
df.isnull()

,Student ID,student_name,gender,grade,school_name,reading_score,math_score
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...
39165,False,False,False,False,False,False,False
39166,False,False,False,False,False,False,False
39167,False,False,False,False,False,False,False
39168,False,False,False,False,False,False,False
39169,False,False,False,False,False,False,False

In [113]:
df.notnull()

,Student ID,student_name,gender,grade,school_name,reading_score,math_score
0,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...
39165,True,True,True,True,True,True,True
39166,True,True,True,True,True,True,True
39167,True,True,True,True,True,True,True
39168,True,True,True,True,True,True,True
39169,True,True,True,True,True,True,True

In [114]:
df.dropna()

,Student ID,student_name,gender,grade,school_name,reading_score,math_score
0,0,Paul Bradley,M,9th,Huang High School,66,79
1,1,Victor Smith,M,12th,Huang High School,94,61
2,2,Kevin Rodriguez,M,12th,Huang High School,90,60
3,3,Dr. Richard Scott,M,12th,Huang High School,67,58
4,4,Bonnie Ray,F,9th,Huang High School,97,84
...,...,...,...,...,...,...,...
39165,39165,Donna Howard,F,12th,Thomas High School,99,90
39166,39166,Dawn Bell,F,10th,Thomas High School,95,70
39167,39167,Rebecca Tanner,F,9th,Thomas High School,73,84
39168,39168,Desiree Kidd,F,10th,Thomas High School,99,90
39169,39169,Carolyn Jackson,F,11th,Thomas High School,95,75

In [115]:
df.notnull()

,Student ID,student_name,gender,grade,school_name,reading_score,math_score
0,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...
39165,True,True,True,True,True,True,True
39166,True,True,True,True,True,True,True
39167,True,True,True,True,True,True,True
39168,True,True,True,True,True,True,True
39169,True,True,True,True,True,True,True

In [116]:
fill_df = pd.read_csv('Resources/missing_grades.csv')

In [117]:
fill_df.fillna(0)

   Student ID       student_name gender grade  reading_score  math_score
0           0       Paul Bradley      M   9th           66.0        79.0
1           1       Victor Smith      M  12th           94.0        61.0
2           2    Kevin Rodriguez      M  12th            0.0        60.0
3           3  Dr. Richard Scott      M  12th           67.0        58.0
4           4         Bonnie Ray      F   9th           97.0        84.0
5           5      Bryan Miranda      M   9th           94.0         0.0
6           6      Sheena Carter      F  11th           82.0        80.0
7           7       Nicole Baker      F  12th           96.0        69.0

In [118]:
df.dtypes

Student ID        int64
student_name     object
gender           object
grade            object
school_name      object
reading_score     int64
math_score        int64
dtype: object

In [119]:
#remove prefixes
name_list=df['student_name'].tolist()
for name in name_list:
    print(name.split(), len(name.split()))

e'] 2
['Savannah', 'Smith'] 2
['Heather', 'Hunter'] 2
['Lisa', 'Tucker'] 2
['Renee', 'Moore'] 2
['Nicole', 'White', 'MD'] 3
['Keith', 'King'] 2
['Amanda', 'Skinner', 'MD'] 3
['Marcus', 'Wallace'] 2
['James', 'Horton'] 2
['Darrell', 'Simpson'] 2
['Diane', 'Rush'] 2
['Christine', 'Guerrero'] 2
['Rita', 'Perez'] 2
['Sarah', 'Williams'] 2
['Jason', 'Key'] 2
['Christine', 'Smith'] 2
['Jennifer', 'Dixon'] 2
['Timothy', 'Wilson'] 2
['Maxwell', 'Anderson'] 2
['Christina', 'Robinson'] 2
['Abigail', 'Durham'] 2
['Charlotte', 'Graham'] 2
['Tanya', 'Barnes'] 2
['Theresa', 'Gentry'] 2
['Donald', 'Nicholson'] 2
['Nathan', 'Smith'] 2
['Sarah', 'Briggs'] 2
['Joshua', 'Thomas'] 2
['Alexander', 'Wilson'] 2
['David', 'Smith'] 2
['Rebecca', 'Reilly'] 2
['Paul', 'Bowers'] 2
['Teresa', 'Chapman'] 2
['Kimberly', 'Case'] 2
['Guy', 'Goodwin'] 2
['Brenda', 'Rivera'] 2
['Gregory', 'Shepherd'] 2
['Kenneth', 'Simon'] 2
['James', 'Stone'] 2
['Scott', 'Smith'] 2
['Kevin', 'Costa'] 2
['Kayla', 'Williams'] 2
['Joshua', 'Burch'] 2
['Emily', 'Washington'] 2
['Elizabeth', 'Graham'] 2
['Kristy', 'Perry'] 2
['Stacey', 'Rodriguez'] 2
['Brittany', 'Harper'] 2
['Robert', 'Pollard'] 2
['Heidi', 'Gomez'] 2
['Mark', 'White'] 2
['Dustin', 'Meyer'] 2
['Stephanie', 'Pham'] 2
['Jeffery', 'Howard'] 2
['Christina', 'Owen'] 2
['Ana', 'Ellis'] 2
['Evan', 'Jones'] 2
['William', 'Schmidt'] 2
['Elizabeth', 'Johnson'] 2
['Ronald', 'Yates'] 2
['Kenneth', 'Collins'] 2
['Stacey', 'Jennings'] 2
['Brandy', 'Cox'] 2
['Ann', 'Garcia'] 2
['David', 'Young'] 2
['Steven', 'Thompson'] 2
['Kaitlyn', 'Davis'] 2
['Patricia', 'Maddox'] 2
['Dylan', 'Ray'] 2
['Sharon', 'Larson'] 2
['Marc', 'Short'] 2
['John', 'Atkins'] 2
['Eugene', 'Johnson'] 2
['Terry', 'Torres'] 2
['Eric', 'Huff'] 2
['Joseph', 'Kim'] 2
['Katie', 'Neal'] 2
['Amy', 'Vega'] 2
['Daniel', 'Wilson'] 2
['Kurt', 'Martinez'] 2
['Dennis', 'Rodriguez'] 2
['Elaine', 'Stephens'] 2
['Melissa', 'Graves'] 2
['Adrienne', 'Turner', 'MD'] 3
['Sandra', 'Franco'] 2
['Adam', 'Woods'] 2
['Patrick', 'Joyce'] 2
['Tanya', 'Chen'] 2
['Tracy', 'Dawson'] 2
['Lisa', 'Coleman'] 2
['Brenda', 'Lloyd'] 2
['Brianna', 'Frey'] 2
['Michael', 'Green'] 2
['Megan', 'Page'] 2
['Jordan', 'Long'] 2
['Tracy', 'Lewis'] 2
['Christine', 'Sellers'] 2
['Angela', 'Berger'] 2
['Donald', 'Evans'] 2
['Scott', 'Rowe'] 2
['Veronica', 'Drake'] 2
['David', 'Cohen'] 2
['Mark', 'Rice'] 2
['Jesse', 'Reyes'] 2
['Nicole', 'Ritter'] 2
['Lisa', 'Gentry'] 2
['Terry', 'Scott', 'Jr.'] 3
['Cesar', 'Rodriguez', 'DVM'] 3
['Jennifer', 'Gay', 'MD'] 3
['David', 'House'] 2
['Michael', 'Moore'] 2
['Jared', 'Woodward'] 2
['Ashley', 'Black'] 2
['Adam', 'Hinton'] 2
['Rebecca', 'Sanchez'] 2
['Daniel', 'Harris'] 2
['Angie', 'Vance'] 2
['Zachary', 'Davis'] 2
['Joshua', 'Glass'] 2
['Scott', 'Mack'] 2
['Diane', 'Morse'] 2
['Lori', 'Jenkins'] 2
['Paul', 'Garcia'] 2
['Jonathan', 'Dunn'] 2
['Dustin', 'Butler'] 2
['Cody', 'Cortez'] 2
['Bridget', 'Benitez'] 2
['Mr.', 'Earl', 'Thompson'] 3
['Tracie', 'Stewart'] 2
['Brenda', 'Le'] 2
['Jennifer', 'Combs'] 2
['Elizabeth', 'Stout']2
['Edward', 'Lopez'] 2
['Timothy', 'Baird'] 2
['Drew', 'Jones'] 2
['Kevin', 'Gordon'] 2
['Andrew', 'Anthony'] 2
['David', 'Garner'] 2
['Dawn', 'Richards'] 2
['Zachary', 'Sanchez'] 2
['Paul', 'Butler'] 2
['Heidi', 'Rhodes'] 2
['Kimberly', 'Duncan'] 2
['Andrew', 'Jones'] 2
['Scott', 'Walters'] 2
['Travis', 'Johnson'] 2
['Taylor', 'Owen'] 2
['Ryan', 'Reed'] 2
['Erin', 'Miller'] 2
['Tiffany', 'Alvarez'] 2
['Donna', 'Ramirez'] 2
['David', 'Taylor'] 2
['Jacob', 'Roberts'] 2
['John', 'Small'] 2
['Robert', 'Lloyd'] 2
['Joe', 'Ewing'] 2
['William', 'Carter'] 2
['Miss', 'Melinda', 'Thomas'] 3
['Jill', 'Mckinney'] 2
['John', 'Dunn'] 2
['Jordan', 'Martinez'] 2
['Mary', 'Nixon', 'MD'] 3
['Kristin', 'Taylor'] 2
['Ashley', 'Jimenez'] 2
['Jessica', 'Hill'] 2
['Laurie', 'Fowler'] 2
['Michael', 'Johnson'] 2
['Kevin', 'Foster'] 2
['Michael', 'Stevens'] 2
['Tracy', 'Noble'] 2
['Daniel', 'Schultz'] 2
['Bridget', 'Robles'] 2
['Erin', 'Mccann'] 2
['Paul', 'Hayes'] 2
['Glenn', 'Mercer'] 2
['Charles', 'Flores'] 2
['Melissa', 'Wilson'] 2
['Tim', 'Harris'] 2
['John', 'Stuart'] 2
['Kim', 'Williams'] 2
['Andrew', 'Gomez'] 2
['Beverly', 'Whitney'] 2
['Eric', 'Cox'] 2
['Leslie', 'Kelly', 'MD'] 3
['Eric', 'Kelley'] 2
['Olivia', 'Hernandez'] 2
['Patrick', 'Garcia'] 2
['Teresa', 'Schultz'] 2
['Kim', 'Peck'] 2
['Laura', 'Murphy'] 2
['George', 'Green'] 2
['Richard', 'Bowman'] 2
['Jasmine', 'Garcia'] 2
['Victoria', 'Harrell'] 2
['Julie', 'Nelson'] 2
['Mrs.', 'Kristen', 'Gonzalez'] 3
['Michael', 'Carter', 'MD'] 3
['Arthur', 'Martinez'] 2
['James', 'Cruz'] 2
['Brian', 'Monroe'] 2
['Michael', 'Booth'] 2
['Daniel', 'Simpson'] 2
['Kenneth', 'Smith'] 2
['Joseph', 'Mitchell'] 2
['Allen', 'Payne'] 2
['Lisa', 'Ward'] 2
['Teresa', 'Miller'] 2
['Daniel', 'Wallace'] 2
['Sheena', 'Hill'] 2
['Sarah', 'Scott'] 2
['Michael', 'James'] 2
['Angela', 'Thompson'] 2
['Lindsay', 'Ortiz'] 2
['Catherine', 'Wilson'] 2
['Jill', 'Kim'] 2
['Lauren', 'Wilson'] 2
['Stacey', 'Lee'] 2
['Carmen', 'Kim'] 2
['Jennifer', 'Weaver'] 2
['Kristi', 'Castillo'] 2
['Matthew', 'Perez'] 2
['Diana', 'Mcdaniel'] 2
['Julia', 'King'] 2
['Susan', 'Thomas'] 2
['Lisa', 'Price'] 2
['Nancy', 'Hopkins'] 2
['Danny', 'Miller'] 2
['Paul', 'Ewing'] 2
['Frank', 'Davis'] 2
['Jeffrey', 'Schultz'] 2
['Misty', 'Nguyen'] 2
['Leroy', 'Shaffer'] 2
['Raymond', 'Hawkins'] 2
['Robert', 'Lewis'] 2
['Anna', 'Jacobs'] 2
['Nathan', 'Adams'] 2
['Christy', 'Ryan'] 2
['Madison', 'Palmer'] 2
['Christina', 'Hall'] 2
['Charles', 'Dickson'] 2
['Pamela', 'Thompson'] 2
['Meghan', 'Williams'] 2
['Gerald', 'Jones'] 2
['Tara', 'Simpson'] 2
['Ryan', 'Fernandez'] 2
['Marissa', 'Wilson'] 2
['Heather', 'Leblanc'] 2
['Andrea', 'Lee'] 2
['Erica', 'Singh'] 2
['Matthew', 'Crane'] 2
['Jennifer', 'Weaver'] 2
['Brian', 'Thomas'] 2
['Elizabeth', 'Lamb'] 2
['Dakota', 'Marshall'] 2
['Kelly', 'Donaldson'] 2
['Donald', 'Scott'] 2
['Mark', 'Smith'] 2
['Todd', 'Johnson'] 2
['Robin', 'Mathis'] 2
['Carlos', 'Gutierrez'] 2
['Katherine', 'Porter'] 2
['Denise', 'Perry'] 2
['Andrew', 'Nelson'] 2
['Michael', 'Hartman'] 2
['Andrea', 'Sanchez'] 2
['Ronnie', 'Powell'] 2
['Matthew', 'Davis'] 2
['Kristina', 'Morrison'] 2
['Kevin', 'Pierce'] 2
['Frank', 'Mitchell'] 2
['Tony', 'Hoover'] 2
['Jessica', 'Roach'] 2
['Danielle', 'Rodriguez'] 2
['Tracy', 'Nguyen'] 2
['Kelly', 'Bridges'] 2
['Joseph', 'Mcgrath'] 2
['Austin', 'Wilcox'] 2
['Katherine', 'Sims'] 2
['Mary', 'Miller'] 2
['Martin', 'Taylor'] 2
['Madison', 'Suarez'] 2
['Betty', 'Campbell'] 2
['Anna', 'Jackson'] 2
['Anthony', 'Reynolds'] 2
['Joseph', 'Perez', 'DDS'] 3
['Matthew', 'Dougherty'] 2
['Angela', 'Hill'] 2
['Stephanie', 'Long'] 2
['Kathy', 'Gonzales'] 2
['Kayla', 'Myers'] 2
['Edward', 'Jones'] 2
['Tiffany', 'Cook'] 2
['Bradley', 'Miller'] 2
['Lisa', 'Blackburn'] 2
['Sara', 'Williams'] 2
['Gregory', 'Howell'] 2
['Sarah', 'Allen'] 2
['Russell', 'Schmitt'] 2
['Peter', 'Stone'] 2
['Gerald', 'Estes'] 2
['Holly', 'Moore'] 2
['Allison', 'Webb'] 2
['Steven', 'Reynolds'] 2
['Mrs.', 'Alice', 'Warren'] 3
['Nichole', 'Perez'] 2
['Autumn', 'Green'] 2
['Eileen', 'Rios'] 2
['Jennifer', 'Cooper'] 2
['Martha', 'Molina'] 2
['Judith', 'Potter'] 2
['Evan', 'Martin'] 2
['Heather', 'Bailey'] 2
['Thomas', 'Clark'] 2
['Brian', 'Arnold'] 2
['Julia', 'Kelley', 'MD'] 3
['Evan', 'Mitchell'] 2
['Susan', 'Roberts'] 2
['Shannon', 'Lopez'] 2
['James', 'Williams'] 2
['Allison', 'Kerr'] 2
['Tiffany', 'Mccarthy'] 2
['Christina', 'Moreno'] 2
['Tony', 'Byrd'] 2
['Jared', 'Mcdonald'] 2
['Zoe', 'Allen'] 2
['Laura', 'Baker'] 2
['James', 'Hale'] 2
['Timothy', 'Obrien'] 2
['Mariah', 'Proctor'] 2
['Mary', 'Rogers'] 2
['Amber', 'Thompson'] 2
['Yolanda', 'Ochoa'] 2
['Debra', 'Rosales'] 2
['Joseph', 'Wood'] 2
['Andre', 'Fisher'] 2
['David', 'Coffey', 'PhD'] 3
['Kelly', 'Hernandez'] 2
['Cheryl', 'Diaz'] 2
['Linda', 'Chambers'] 2
['William', 'Sandoval'] 2
['Kristen', 'Crawford'] 2
['Erica', 'King'] 2
['Eric', 'Carson'] 2
['James', 'Cruz'] 2
['Nathan', 'Maldonado'] 2
['David', 'Rodriguez'] 2
['Justin', 'Williams'] 2
['Jason', 'Shaw'] 2
['Mrs.', 'Pam', 'Wolf', 'DDS'] 4
['Catherine', 'Cross'] 2
['Melissa', 'Johnson'] 2
['Lori', 'Wilkerson'] 2
['Katherine', 'Hardin'] 2
['Kevin', 'Vasquez'] 2
['Stephanie', 'Franklin'] 2
['Edward', 'Parrish'] 2
['Caitlin', 'Williams'] 2
['Mark', 'Sanchez'] 2
['Lindsey', 'Benson'] 2
['Rachel', 'Miller'] 2
['Andrea', 'Mack'] 2
['Sarah', 'Brown'] 2
['Lisa', 'Fitzgerald'] 2
['Jessica', 'Prince'] 2
['Jeffery', 'King'] 2
['Travis', 'Spencer'] 2
['Erica', 'Tucker'] 2
['Lauren', 'Casey'] 2
['Emily', 'Williams'] 2
['Kevin', 'Thomas'] 2
['Amanda', 'Small'] 2
['Kerri', 'Torres'] 2
['Danny', 'Powers'] 2
['Jessica', 'Cohen'] 2
['Jeffrey', 'Duarte'] 2
['Crystal', 'Fields'] 2
['Henry', 'Tucker'] 2
['Kenneth', 'Carter'] 2
['Courtney', 'Miller'] 2
['Eric', 'Benson'] 2
['Joshua', 'Vargas'] 2
['Rebekah', 'Perkins'] 2
['Mr.', 'Ryan', 'Thomas'] 3
['Pamela', 'Brooks'] 2
['Bridget', 'Shah'] 2
['Cassidy', 'Carter'] 2
['Kelly', 'Michael'] 2
['Michael', 'Flores'] 2
['Robert', 'Wilcox'] 2
['Christopher', 'Melton'] 2
['Stephanie', 'Johnson'] 2
['Thomas', 'Payne'] 2
['Elizabeth', 'Miller'] 2
['Pamela', 'Thomas'] 2
['Victoria', 'Nguyen'] 2
['Brian', 'Mills'] 2
['Deborah', 'Holloway'] 2
['David', 'Gray'] 2
['Kathleen', 'Lewis'] 2
['Michelle', 'Pratt'] 2
['Steven', 'Brown'] 2
['James', 'Wallace'] 2
['Amy', 'Hayes'] 2
['Matthew', 'Nunez'] 2
['Joseph', 'Gentry'] 2
['Heidi', 'Johnson'] 2
['Nancy', 'Harris'] 2
['Ashley', 'Hill'] 2
['Jeffery', 'Abbott'] 2
['Gregory', 'Morgan', 'MD'] 3
['Daniel', 'Herrera'] 2
['Pamela', 'Salinas'] 2
['Sarah', 'Johnson'] 2
['Jason', 'Gonzalez'] 2
['Richard', 'Alexander'] 2
['Randy', 'Richards'] 2
['Adriana', 'Reyes'] 2
['Carrie', 'Meyer'] 2
['Phillip', 'Lin'] 2
['Daniel', 'Mack'] 2
['Kimberly', 'Roach'] 2
['Dakota', 'Barry'] 2
['Latoya', 'Graham'] 2
['Manuel', 'Lane'] 2
['Kathy', 'Jones'] 2
['Charles', 'Petty'] 2
['Brent', 'Matthews'] 2
['Amy', 'Lucas'] 2
['Christopher', 'Black'] 2
['Alyssa', 'Burns'] 2
['Jeffrey', 'Evans'] 2
['Dr.', 'Carol', 'Williams'] 3
['Kelly', 'Chambers'] 2
['Kayla', 'Anderson'] 2
['Andrew', 'Ellis'] 2
['Michelle', 'Cook'] 2
['Victoria', 'Martin'] 2
['Joshua', 'Underwood'] 2
['Matthew', 'Howard'] 2
['Michelle', 'Gray'] 2
['Ms.', 'Rebecca', 'Gonzales'] 3
['James', 'Schmidt'] 2
['Mrs.', 'Samantha', 'Glover'] 3
['Theresa', 'Nelson'] 2
['Raymond', 'Jackson'] 2
['Yvette', 'Ashley'] 2
['David', 'Moss'] 2
['Elizabeth', 'Howard'] 2
['Shelby', 'George'] 2
['Justin', 'Frazier'] 2
['Chelsea', 'Adams'] 2
['Erika', 'Payne'] 2
['Anna', 'Decker', 'MD'] 3
['Linda', 'Mccann'] 2
['Leslie', 'Fowler'] 2
['Robin', 'Morris'] 2
['Samuel', 'Campbell'] 2
['Angela', 'Pennington'] 2
['Andrew', 'Stephenson'] 2
['Sandra', 'Mcbride'] 2
['Hailey', 'Lopez', 'DDS'] 3
['Walter', 'Stokes'] 2
['Dave', 'Diaz'] 2
['Robert', 'Coleman'] 2
['Andrew', 'Gibson'] 2
['Kristina', 'Snow'] 2
['Michael', 'Martinez'] 2
['Patrick', 'Jenkins'] 2
['Larry', 'Scott'] 2
['Dana', 'Kidd'] 2
['Amber', 'Lewis'] 2
['Alan', 'Simmons'] 2
['Rebecca', 'Joseph'] 2
['Brian', 'Acosta'] 2
['Kimberly', 'Erickson'] 2
['Cynthia', 'Maldonado'] 2
['Anthony', 'Flores'] 2
['Jacob', 'Mills'] 2
['Mr.', 'James', 'Baker'] 3
['Cynthia', 'Martin'] 2
['Natalie', 'Taylor'] 2
['Ashley', 'Mcdonald'] 2
['Kirk', 'Vaughn'] 2
['Dustin', 'Ray'] 2
['Gabriel', 'Miller'] 2
['Deborah', 'Griffith'] 2
['Christopher', 'Rose'] 2
['Maria', 'Kirk'] 2
['Nancy', 'Fox'] 2
['Heather', 'Davis'] 2
['Taylor', 'Smith'] 2
['Mrs.', 'Amber', 'Gonzalez'] 3
['Leslie', 'Nelson'] 2
['John', 'Escobar'] 2
['Robert', 'Harper'] 2
['Angela', 'Mooney'] 2
['Chad', 'Dudley'] 2
['Richard', 'Lee'] 2
['Elizabeth', 'Ross'] 2
['Cheryl', 'Garner'] 2
['Debbie', 'Garrison'] 2
['Nicole', 'Shaw'] 2
['Kayla', 'Jones'] 2
['Cristina', 'Drake'] 2
['Mr.', 'Jason', 'Patel', 'Jr.'] 4
['Tina', 'Salazar'] 2
['Timothy', 'Ward'] 2
['Jeremiah', 'Arroyo'] 2
['Ryan', 'Barnes'] 2
['Jennifer', 'Robinson'] 2
['Matthew', 'Walsh'] 2
['Marissa', 'Reed'] 2
['Matthew', 'Ritter'] 2
['Jennifer', 'Kelley'] 2
['David', 'Silva'] 2
['Reginald', 'Johnson'] 2
['Logan', 'White'] 2
['Cheryl', 'Reynolds'] 2
['Kelly', 'Mclean'] 2
['Laura', 'Richardson'] 2
['Maria', 'Davis'] 2
['Amy', 'Anderson'] 2
['Timothy', 'Smith'] 2
['Laura', 'Kidd'] 2
['Lydia', 'Gomez'] 2
['Stephanie', 'Walker', 'DDS'] 3
['Joseph', 'Daniels'] 2
['Tracey', 'Hernandez'] 2
['Barry', 'Bridges'] 2
['David', 'Lin'] 2
['Ariel', 'Reynolds'] 2
['Mr.', 'Timothy', 'Scott'] 3
['Jonathan', 'Crawford'] 2
['Natalie', 'Dunn'] 2
['Shawn', 'Williams'] 2
['Jennifer', 'Parsons'] 2
['Adam', 'Haley'] 2
['Mary', 'Berry'] 2
['Amy', 'Payne'] 2
['Emily', 'Neal'] 2
['Ashlee', 'Cooley'] 2
['Kenneth', 'Lane'] 2
['Joseph', 'Garcia'] 2
['Dr.', 'Michael', 'Sullivan', 'DDS'] 4
['Christopher', 'Henderson'] 2
['Javier', 'Zamora'] 2
['Theresa', 'Oconnor'] 2
['Jamie', 'Campbell'] 2
['Paige', 'Bates'] 2
['Kelly', 'Lane'] 2
['Steven', 'Hernandez'] 2
['Kristen', 'Sims'] 2
['Todd', 'Fields'] 2
['Larry', 'Holmes'] 2
['Michael', 'Miller'] 2
['Doris', 'Taylor'] 2
['Margaret', 'Hodge'] 2
['Vanessa', 'Burton'] 2
['Debra', 'Thomas'] 2
['Donna', 'Ellison'] 2
['Mrs.', 'Brittney', 'Schultz', 'DVM'] 4
['Sean', 'Morrison'] 2
['Dillon', 'Davidson'] 2
['Timothy', 'Conner'] 2
['Catherine', 'Romero'] 2
['Michael', 'Williams'] 2
['Susan', 'Greer'] 2
['John', 'Bentley'] 2
['Craig', 'Wells'] 2
['Aaron', 'Martin'] 2
['Alexandra', 'Wright'] 2
['Elizabeth', 'Mccoy'] 2
['Steven', 'Johnson'] 2
['Donna', 'Morales'] 2
['Sean', 'Morales'] 2
['Ashley', 'Park'] 2
['Kristy', 'Ruiz'] 2
['Jason', 'Fisher'] 2
['Gloria', 'Hamilton'] 2
['Evan', 'Moreno'] 2
['Betty', 'Jackson'] 2
['Courtney', 'Santos'] 2
['Lisa', 'Jackson'] 2
['Keith', 'Petty'] 2
['Randy', 'Travis'] 2
['Michael', 'Morgan'] 2
['Stephen', 'Miller'] 2
['Brian', 'Burton'] 2
['Debra', 'Williams'] 2
['Dr.', 'Frances', 'Romero'] 3
['Edgar', 'Garcia'] 2
['Eric', 'Williams'] 2
['Louis', 'Elliott'] 2
['Robin', 'Jones'] 2
['Lynn', 'Duncan'] 2
['Anthony', 'Nunez'] 2
['William', 'Newman'] 2
['Taylor', 'Salinas'] 2
['Lauren', 'Kelly'] 2
['Jordan', 'Hamilton'] 2
['Joel', 'Curry'] 2
['Andres', 'Reyes'] 2
['Thomas', 'Pham'] 2
['Gregory', 'Graham'] 2
['Nicholas', 'White'] 2
['Kevin', 'Rowe'] 2
['Michael', 'Palmer'] 2
['Jim', 'Carrillo'] 2
['Katherine', 'Russell'] 2
['Spencer', 'Johnson'] 2
['Mary', 'Taylor'] 2
['Henry', 'Burke'] 2
['Kelly', 'Weaver'] 2
['Christopher', 'Johnson'] 2
['Janice', 'Martin'] 2
['Taylor', 'Cooke'] 2
['Chad', 'Medina'] 2
['Ashley', 'Romero'] 2
['Samantha', 'Steele'] 2
['Stacey', 'Taylor'] 2
['Vicki', 'Meyer'] 2
['Taylor', 'Thomas'] 2
['Peggy', 'King'] 2
['Alexandra', 'Williams'] 2
['Sandra', 'Griffin'] 2
['Yolanda', 'Le'] 2
['Dennis', 'Bradford'] 2
['Ann', 'Duffy'] 2
['Rachel', 'Butler'] 2
['Robert', 'Smith'] 2
['Melissa', 'Hooper'] 2
['Amber', 'Anderson'] 2
['George', 'Collins'] 2
['Robert', 'Reid'] 2
['Stephen', 'Jones'] 2
['Brenda', 'Taylor'] 2
['Denise', 'Foster'] 2
['Alexandria', 'Carpenter'] 2
['Luke', 'Brown'] 2
['Michael', 'Clements'] 2
['Tiffany', 'Francis'] 2
['Shannon', 'Carson'] 2
['Tracey', 'Liu'] 2
['Logan', 'Osborn'] 2
['John', 'Roberson'] 2
['Dennis', 'Anderson'] 2
['Kelly', 'Diaz'] 2
['Chad', 'Carr'] 2
['John', 'Bailey'] 2
['Dennis', 'Peters'] 2
['Laura', 'Bennett', 'DDS'] 3
['Charles', 'Brown'] 2
['Marissa', 'Richardson'] 2
['Amy', 'Davis'] 2
['Andrea', 'Johnson'] 2
['Jessica', 'Brewer'] 2
['Ashley', 'Lynch'] 2
['Christine', 'Howell'] 2
['Luis', 'Cannon'] 2
['Jennifer', 'Phillips'] 2
['Maria', 'Davis'] 2
['Thomas', 'Anderson'] 2
['Annette', 'Davis'] 2
['David', 'Price'] 2
['Christina', 'Carter'] 2
['Laura', 'Smith'] 2
['Stacey', 'Mitchell'] 2
['Michelle', 'Davis'] 2
['Shane', 'Lindsey'] 2
['Denise', 'Moore'] 2
['Kendra', 'Flynn'] 2
['Austin', 'Burke'] 2
['David', 'Chapman'] 2
['Malik', 'Thomas'] 2
['Cynthia', 'Lloyd'] 2
['Theresa', 'Ryan'] 2
['Amber', 'Reynolds'] 2
['Allen', 'Goodwin', 'DDS'] 3
['Terry', 'Diaz'] 2
['Jeffrey', 'Davis'] 2
['Diana', 'Jones'] 2
['Mia', 'Gould'] 2
['Katherine', 'Johnson'] 2
['Michael', 'Williams'] 2
['Joseph', 'Turner'] 2
['Peter', 'Potter'] 2
['Ryan', 'Kim'] 2
['Janice', 'Yoder'] 2
['Carolyn', 'Webb'] 2
['Elizabeth', 'Bush'] 2
['Jaime', 'Edwards'] 2
['Bethany', 'Smith'] 2
['Wanda', 'Grimes'] 2
['Karina', 'Allison'] 2
['Timothy', 'Smith'] 2
['Jason', 'Harris'] 2
['Thomas', 'Smith'] 2
['John', 'Whitaker'] 2
['Kimberly', 'Brown', 'MD'] 3
['Barbara', 'Miller'] 2
['Madeline', 'Lopez'] 2
['Carlos', 'Fischer'] 2
['Amy', 'Collins'] 2
['Abigail', 'White'] 2
['Joanne', 'Strickland'] 2
['Maria', 'Hernandez'] 2
['Sandra', 'Mcdowell'] 2
['Kristin', 'Krause'] 2
['Alicia', 'Reese'] 2
['Isaac', 'Holt'] 2
['Jonathan', 'Garza'] 2
['Phillip', 'Smith'] 2
['Amanda', 'Vazquez'] 2
['Jaime', 'Holland'] 2
['Tina', 'Rhodes'] 2
['John', 'Wells'] 2
['Lindsay', 'Dougherty'] 2
['Caitlyn', 'Vega'] 2
['Kevin', 'Campbell'] 2
['Michael', 'Everett'] 2
['Christian', 'Martinez'] 2
['Chad', 'Rivera'] 2
['Amanda', 'Ferrell'] 2
['Natasha', 'Murphy'] 2
['Kathleen', 'Cook'] 2
['Steven', 'Lewis', 'Jr.'] 3
['Raymond', 'Hardy'] 2
['Michael', 'Hill'] 2
['Mary', 'Summers'] 2
['Barbara', 'Cardenas'] 2
['Angela', 'Garcia', 'DDS'] 3
['Ronnie', 'Craig'] 2
['Chad', 'Miller'] 2
['Margaret', 'Perez'] 2
['Michael', 'Rodriguez'] 2
['Preston', 'Davis'] 2
['Michael', 'Reed'] 2
['Matthew', 'Ball'] 2
['Larry', 'Robinson'] 2
['Kyle', 'Gonzalez'] 2
['Sarah', 'Atkinson'] 2
['William', 'Foster', 'PhD'] 3
['Michael', 'James'] 2
['Michael', 'Strong'] 2
['Kenneth', 'Moore'] 2
['Brittney', 'Coleman'] 2
['Jacob', 'Stein'] 2
['Jason', 'Rodgers'] 2
['Jose', 'Newton'] 2
['John', 'Wheeler'] 2
['April', 'Ellis'] 2
['Caleb', 'Young'] 2
['Derrick', 'Alexander'] 2
['Jasmine', 'Li'] 2
['Michael', 'Higgins'] 2
['Joel', 'French'] 2
['Sheri', 'Taylor'] 2
['Vanessa', 'Wagner'] 2
['Amanda', 'Ramirez'] 2
['Susan', 'Gates'] 2
['Jason', 'Lawrence'] 2
['Jonathan', 'Alvarez'] 2
['Joshua', 'Graham'] 2
['Jeffery', 'Gomez'] 2
['Sara', 'Hughes'] 2
['Sandy', 'Johns'] 2
['Melissa', 'Carter'] 2
['Emma', 'Foley'] 2
['Jennifer', 'Harris'] 2
['Gloria', 'Wilson'] 2
['Angela', 'Daniels'] 2
['Marcus', 'Morgan'] 2
['Joanna', 'Allen'] 2
['Lisa', 'Kennedy'] 2
['Joseph', 'Stewart'] 2
['Lindsey', 'Thompson'] 2
['Lori', 'Dickson'] 2
['Jeremy', 'Edwards'] 2
['Joseph', 'Burgess'] 2
['Antonio', 'Kirk'] 2
['Renee', 'Mcdonald'] 2
['Kelli', 'Barnes'] 2
['Lucas', 'Williams', 'Jr.'] 3
['Kathleen', 'Barr'] 2
['Nancy', 'Silva'] 2
['Rachel', 'Murphy'] 2
['Rhonda', 'Rodriguez'] 2
['Tammy', 'Torres'] 2
['Jennifer', 'White'] 2
['Carrie', 'Stewart'] 2
['Karen', 'Rogers'] 2
['Dr.', 'Kimberly', 'Page'] 3
['Catherine', 'Mendoza'] 2
['Stacy', 'Wells'] 2
['Crystal', 'Smith'] 2
['Ernest', 'Lawrence'] 2
['Sharon', 'Nguyen'] 2
['Mary', 'Coffey'] 2
['Kimberly', 'Pruitt'] 2
['Richard', 'Mcdonald'] 2
['Gregory', 'Taylor'] 2
['Joseph', 'Ho'] 2
['Anna', 'Smith'] 2
['Daniel', 'Best'] 2
['Terri', 'Johnston'] 2
['Katherine', 'Harrison'] 2
['Megan', 'Carson'] 2
['Stephanie', 'Wilson'] 2
['Samantha', 'Johnson'] 2
['Andrew', 'Merritt'] 2
['Susan', 'Simon'] 2
['Maria', 'Shields'] 2
['Samuel', 'Casey'] 2
['Robert', 'Wood'] 2
['Jonathan', 'Mueller'] 2
['Diane', 'Miller'] 2
['Brett', 'Arnold'] 2
['Brian', 'Williams'] 2
['Shawn', 'Hayden'] 2
['Emily', 'Gomez'] 2
['Kerri', 'Berger'] 2
['Laura', 'Webster'] 2
['Elizabeth', 'Aguirre'] 2
['Victoria', 'Bailey'] 2
['Monica', 'Hampton'] 2
['Catherine', 'Lee'] 2
['Cheyenne', 'Hernandez'] 2
['Jonathan', 'Sullivan'] 2
['Deborah', 'Higgins', 'DDS'] 3
['Steven', 'Jackson'] 2
['Cristian', 'Webster'] 2
['Audrey', 'Fry'] 2
['Michael', 'Carroll'] 2
['Raymond', 'Hawkins'] 2
['Christopher', 'Wilson'] 2
['Glenda', 'Fletcher'] 2
['Jennifer', 'Hamilton'] 2
['Shannon', 'Williams'] 2
['Lori', 'Moore'] 2
['William', 'Hubbard'] 2
['Bradley', 'Johnson'] 2
['John', 'Brooks'] 2
['Stephanie', 'Contreras'] 2
['Kristen', 'Gonzalez'] 2
['Kari', 'Holloway'] 2
['Kimberly', 'Cabrera'] 2
['Katie', 'Weaver'] 2
['April', 'Reyes'] 2
['Derek', 'Weeks'] 2
['John', 'Reese'] 2
['Joseph', 'Anthony'] 2
['Donna', 'Howard'] 2
['Dawn', 'Bell'] 2
['Rebecca', 'Tanner'] 2
['Desiree', 'Kidd'] 2
['Carolyn', 'Jackson'] 2

In [120]:
#separate names with 3 
fixer_uppers=[]
for name in name_list:
    if len(name.split()) >= 3:
        fixer_uppers.append(name)
len(fixer_uppers)

1531

In [121]:
#longest prefix is "Miss"
#print(fixer_uppers)

In [122]:
#isolate prefixes "Miss" is longest at 4 characters. 
prefix_list=[]
for name in fixer_uppers:
    if len(name.split()[0]) <= 4:
        prefix_list.append(name.split()[0])
print(prefix_list)

['Dr.', 'Dr.', 'Mr.', 'Dr.', 'Miss', 'Luke', 'Dr.', 'Mrs.', 'Mrs.', 'Mr.', 'Dr.', 'Mr.', 'Mr.', 'Mary', 'Mrs.', 'Mrs.', 'Mr.', 'Tara', 'Dr.', 'Mr.', 'Mrs.', 'Mr.', 'Mr.', 'John', 'Mr.', 'Mrs.', 'Mr.', 'Dr.', 'Mr.', 'Mr.', 'Dale', 'Dr.', 'Dr.', 'Dr.', 'Ms.', 'Dr.', 'Dr.', 'Mr.', 'Mrs.', 'Amy', 'Mr.', 'Dr.', 'Mr.', 'Mr.', 'Mrs.', 'Mrs.', 'Mr.', 'Lisa', 'Mr.', 'Dr.', 'Mr.', 'Mr.', 'Mr.', 'Dr.', 'Mr.', 'Mark', 'Mrs.', 'Dr.', 'Dr.', 'Miss', 'Mr.', 'Miss', 'Mr.', 'Mrs.', 'Mr.', 'Mrs.', 'Mr.', 'Mr.', 'Mr.', 'Dr.', 'Dr.', 'Miss', 'Mr.', 'Mrs.', 'Mr.', 'Tara', 'Dr.', 'Mr.', 'Cody', 'Mr.', 'Dr.', 'Mr.', 'Ms.', 'Dr.', 'Mr.', 'Mrs.', 'Sara', 'Mr.', 'Mrs.', 'Dr.', 'Mr.', 'Dr.', 'Mr.', 'Mrs.', 'Mr.', 'Mr.', 'Mr.', 'Mr.', 'Mr.', 'Dr.', 'Mrs.', 'Mr.', 'Mrs.', 'Dr.', 'Ryan', 'Mrs.', 'Mr.', 'Ms.', 'Mr.', 'Dr.', 'John', 'Mr.', 'Dr.', 'Dr.', 'Mrs.', 'Dr.', 'Mrs.', 'Mr.', 'Mr.', 'Mrs.', 'Dr.', 'Dr.', 'Miss', 'Miss', 'Mr.', 'Mr.', 'Mr.', 'Dr.', 'Dr.', 'Mrs.', 'Mr.', 'Ms.', 'Mr.', 'Miss', 'Tony', 'Dr.', 'Mr.', 'Mr.', 'Mrs.', 'Mr.', 'Mrs.', 'Miss', 'Mrs.', 'Jodi', 'Mr.', 'Mr.', 'Mrs.', 'Mr.', 'Mr.', 'Mrs.', 'Mrs.', 'Mrs.', 'Mr.', 'Mr.', 'Mr.', 'Mrs.', 'Dr.', 'Mr.', 'Mr.', 'Mrs.', 'Mr.', 'Mrs.', 'Mr.', 'Dr.', 'Mr.', 'Mr.', 'Ruth', 'Dr.', 'Mr.', 'Ms.', 'Dr.', 'Mr.', 'Mrs.', 'Mr.', 'Dr.', 'Dr.', 'John', 'Dr.', 'Mr.', 'Mrs.', 'Mrs.', 'Mrs.', 'Dr.', 'Mrs.', 'John', 'Amy', 'Adam', 'Dr.', 'Eric', 'Mrs.', 'Mr.', 'Mrs.', 'Dr.', 'Dr.', 'Kyle', 'Mr.', 'Ms.', 'Lynn', 'Dr.', 'Mr.', 'Jon', 'Mrs.', 'Mrs.', 'Mrs.', 'Dr.', 'Mrs.', 'Dr.', 'Dr.', 'Dr.', 'Mrs.', 'Mrs.', 'Judy', 'Mr.', 'Dr.', 'Mr.', 'Mrs.', 'Dr.', 'Mr.', 'Mr.', 'Mr.', 'Sara', 'Dr.', 'Dr.', 'Mrs.', 'Tara', 'Dr.', 'Mrs.', 'Dr.', 'Miss', 'Mrs.', 'Mr.', 'Dr.', 'Miss', 'Tina', 'Dr.', 'Eric', 'Ms.', 'Ms.', 'Mr.', 'Mrs.', 'Dr.', 'Dr.', 'Mr.', 'Mr.', 'Dr.', 'Mr.', 'Mr.', 'Dr.', 'Miss', 'Dr.', 'Paul', 'Mrs.', 'Mr.', 'Mrs.', 'Mr.', 'Mr.', 'Mr.', 'Dr.', 'Mrs.', 'Dr.', 'Dr.', 'Mrs.', 'Mrs.', 'Dr.', 'Dr.', 'Dr.', 'Mr.', 'Ms.', 'Dr.', 'Mr.', 'Mrs.', 'Dr.', 'Mrs.', 'Dr.', 'Mrs.', 'Mr.', 'Dr.', 'Mrs.', 'Mrs.', 'Mrs.', 'Dr.', 'Dr.', 'Mr.', 'Mr.', 'Mr.', 'Dr.', 'Marc', 'Mr.', 'Dr.', 'Dr.', 'Dr.', 'Mrs.', 'Dr.', 'Mrs.', 'Mrs.', 'Mr.', 'Mrs.', 'Dr.', 'Dr.', 'Dr.', 'Dr.', 'Mr.', 'Dr.', 'Mr.', 'Mrs.', 'Dr.', 'Dr.', 'Dr.', 'Amy', 'Dr.', 'Mr.', 'Mrs.', 'Mr.', 'Mrs.', 'Dr.', 'Dr.', 'Mr.', 'Mrs.', 'Dr.', 'Jill', 'Mary', 'Carl', 'Mr.', 'Dr.', 'Jose', 'Mrs.', 'Mary', 'Ms.', 'Jose', 'Lisa', 'Mrs.', 'Mr.', 'Miss', 'Mr.', 'Eric', 'Mr.', 'Mrs.', 'Mrs.', 'Miss', 'Emma', 'Mrs.', 'Dr.', 'Mrs.', 'Mr.', 'Dr.', 'Mr.', 'Mr.', 'Dr.', 'Dr.', 'Mrs.', 'Dr.', 'Dr.', 'Mr.', 'Mr.', 'Ms.', 'Mr.', 'Gary', 'Mr.', 'Lori', 'Mrs.', 'Mr.', 'Mr.', 'Mrs.', 'Mrs.', 'Noah', 'Dawn', 'Dr.', 'Mr.', 'Mr.', 'Mrs.', 'Mrs.', 'Mrs.', 'Dr.', 'Chad', 'Mr.', 'Paul', 'Mrs.', 'Dr.', 'Mrs.', 'Mrs.', 'Mrs.', 'Dr.', 'Dr.', 'Mrs.', 'Mrs.', 'Dr.', 'Miss', 'Mrs.', 'Eric', 'Dr.', 'Mrs.', 'Dr.', 'Mr.', 'Dr.', 'Adam', 'Mr.', 'Dr.', 'Dr.', 'Mr.', 'Mr.', 'Mr.', 'Mr.', 'Anne', 'Mr.', 'Mrs.', 'Troy', 'Mr.', 'Mrs.', 'Dr.', 'Mr.', 'Mr.', 'Mr.', 'Mr.', 'Miss', 'Mr.', 'Anna', 'John', 'Mr.', 'Mr.', 'Mrs.', 'Eric', 'Mr.', 'Dr.', 'Dr.', 'Mr.', 'Mr.', 'Ryan', 'Mrs.', 'Dr.', 'Emma', 'Mr.', 'Mr.', 'Mrs.', 'Miss', 'Mr.', 'Mr.', 'Mrs.', 'Mrs.', 'Mr.', 'Mr.', 'Mr.', 'Mrs.', 'Mr.', 'Dr.', 'Lisa', 'Mr.', 'Dr.', 'Mrs.', 'John', 'Mrs.', 'Ms.', 'Mrs.', 'Mrs.', 'Dr.', 'Mr.', 'Mrs.', 'Mr.', 'Amy', 'Dr.', 'Mr.', 'Dr.', 'Mrs.', 'Dr.', 'Dr.', 'Lori', 'Mr.', 'Dr.', 'Mrs.', 'Amy', 'Dr.', 'Mrs.', 'Dr.', 'Anne', 'Dr.', 'Mr.', 'Mr.', 'Mr.', 'Mr.', 'Mr.', 'Mrs.', 'Mike', 'Mrs.', 'Todd', 'Mrs.', 'Mr.', 'Mr.', 'Mrs.', 'Dr.', 'Mr.', 'Mrs.', 'Dr.', 'Dr.', 'Mrs.', 'Mrs.', 'Mr.', 'Dr.', 'Mrs.', 'Mrs.', 'Dr.', 'Dr.', 'Miss', 'Mr.', 'Mrs.', 'Dr.', 'Dr.', 'Mrs.', 'Mr.', 'Mrs.', 'Mr.', 'Mr.', 'Dr.', 'Mr.', 'Dr.', 'Mrs.', 'Dr.', 'Ms.', 'Mr.', 'Miss', 'Dr.', 'Miss', 'Dr.', 'Leah', 'Miss', 'Mr.', 'Mr.', 'Dr.', 'Mr.', 'Dr.', 'Dr.', 'Dr.', 'Mr.', 'Dr.', 'Dr.', 'Dr.', 'Mr.', 'Dr.', 'Ian', 'Dr.', 'Mr.', 'Dr.', 'Mr.', 'Dr.', 'Mrs.', 'Miss', 'Dr.', 'Mrs.', 'Ms.', 'Dr.', 'Dr.', 'Mark', 'Mr.', 'Kari', 'Mrs.', 'Mrs.', 'Mr.', 'Mrs.', 'Dr.', 'Dr.', 'Mrs.', 'Dr.', 'Mrs.', 'Kara', 'Mark', 'John', 'Mrs.', 'Dr.', 'Mrs.', 'Mr.', 'Eric', 'John', 'Dr.', 'Mrs.', 'Dr.', 'Mr.', 'Paul', 'Dr.', 'Mrs.', 'Dr.', 'Dr.', 'Dr.', 'Adam', 'Mrs.', 'Ms.', 'Dr.', 'Mrs.', 'Dr.', 'Ms.', 'Mrs.', 'Mr.', 'Mr.', 'Mrs.', 'Dr.', 'Mrs.', 'Mr.', 'Dr.', 'Mr.', 'Dr.', 'Dr.', 'Paul', 'Mrs.', 'Cory', 'Mrs.', 'Dr.', 'Dr.', 'Dr.', 'Mr.', 'Mr.', 'Erin', 'Dr.', 'Dr.', 'Ms.', 'Mrs.', 'Mr.', 'Miss', 'Mr.', 'Mr.', 'Mr.', 'Ms.', 'Mrs.', 'Mr.', 'Mrs.', 'Miss', 'Ms.', 'Dr.', 'Dr.', 'Mrs.', 'Mr.', 'Mrs.', 'John', 'Lisa', 'Mr.', 'Mr.', 'Mrs.', 'Mr.', 'Jon', 'Mrs.', 'Dr.', 'Greg', 'Ms.', 'Mrs.', 'Mr.', 'Mrs.', 'Miss', 'Mr.', 'Dr.', 'Joe', 'Dr.', 'Mark', 'Dr.', 'Mrs.', 'Miss', 'Mr.', 'Mr.', 'Mr.', 'Mrs.', 'Dr.', 'Mr.', 'Mr.', 'Mr.', 'Adam', 'Mr.', 'Mr.', 'Dana', 'Dr.', 'Mr.', 'Dr.', 'Mrs.', 'Mr.', 'Erik', 'Mrs.', 'Dr.', 'Miss', 'Mrs.', 'Ms.', 'Mr.', 'Mr.', 'Mr.', 'John', 'Gail', 'Todd', 'Mr.', 'Mr.', 'Mrs.', 'Ms.', 'Ryan', 'Mrs.', 'Mrs.', 'Dr.', 'Erik', 'Omar', 'Mr.', 'Dr.', 'Cody', 'Ms.', 'Dr.', 'Mrs.', 'Dr.', 'Mr.', 'Mr.', 'Miss', 'Mark', 'Dr.', 'Dr.', 'Mr.', 'Mrs.', 'Mr.', 'Mr.', 'Mr.', 'Mrs.', 'Mr.', 'Mrs.', 'Mr.', 'Dr.', 'Dr.', 'Mr.', 'Mr.', 'Mr.', 'Dr.', 'Miss', 'Mrs.', 'Seth', 'Dr.', 'Mrs.', 'Ryan', 'Mrs.', 'Mrs.', 'Mrs.', 'Mr.', 'Mrs.', 'Dr.', 'Mr.', 'Mrs.', 'Ryan', 'Mrs.', 'Mr.', 'Dr.', 'Dr.', 'Mr.', 'Dr.', 'Dr.', 'Mrs.', 'Ms.', 'Dr.', 'Dr.', 'Mr.', 'Mr.', 'Ms.', 'Dr.', 'Dr.', 'Dr.', 'Mr.', 'Mrs.', 'Mr.', 'Lisa', 'Mr.', 'Dr.', 'Chad', 'Gina', 'Dr.', 'Mr.', 'Mr.', 'Mrs.', 'Amy', 'Mr.', 'Mrs.', 'Mr.', 'Dr.', 'Mr.', 'Dr.', 'Mrs.', 'Lisa', 'Mrs.', 'Dr.', 'Miss', 'Mr.', 'Mr.', 'Ms.', 'Mrs.', 'Mr.', 'Mrs.', 'Mr.', 'Dr.', 'Dr.', 'Mr.', 'Lisa', 'Dr.', 'Mr.', 'Ms.', 'Mrs.', 'Mr.', 'Dr.', 'Dr.', 'Mrs.', 'Sean', 'Dr.', 'Dr.', 'Mr.', 'Mr.', 'Miss', 'Miss', 'Dr.', 'Mr.', 'Dr.', 'Dr.', 'Mrs.', 'Mr.', 'Mrs.', 'Mrs.', 'Dr.', 'Mrs.', 'Dr.', 'Mr.', 'Mrs.', 'Mr.', 'Mr.', 'Todd', 'Dr.', 'Mrs.', 'Mrs.', 'Miss', 'Dr.', 'Mrs.', 'Mr.', 'Mr.', 'Mrs.', 'Adam', 'Mrs.', 'Ms.', 'Tony', 'Dr.', 'Miss', 'Toni', 'Ms.', 'Mr.', 'Mr.', 'Dr.', 'Ms.', 'Dr.', 'Mrs.', 'Dr.', 'Dr.', 'Dr.', 'Jose', 'Dr.', 'Dr.', 'Amy', 'John', 'Mrs.', 'Mr.', 'Mrs.', 'Mrs.', 'Miss', 'Mr.', 'Dr.', 'Mary', 'Mark', 'Dr.', 'Ms.', 'Ms.', 'Dr.', 'Mr.', 'Dr.', 'Miss', 'Mr.', 'Dr.', 'Troy', 'John', 'Dr.', 'Kim', 'Mr.', 'Mr.', 'Miss', 'Mary', 'Mrs.', 'Mrs.', 'Mrs.', 'Mr.', 'Dr.', 'Ms.', 'Mrs.', 'Anna', 'Mr.', 'Mrs.', 'Mr.', 'Mr.', 'Dr.', 'Mrs.', 'Dr.', 'Dr.']

In [123]:
#do the same for suffixes "[-1]""
suffix_list=[]
for name in fixer_uppers:
    if len(name.split()[-1]) <= 3:
        suffix_list.append(name.split()[-1])
print(suffix_list)

['MD', 'MD', 'MD', 'III', 'DVM', 'MD', 'MD', 'MD', 'DDS', 'DVM', 'II', 'MD', 'MD', 'DDS', 'MD', 'DDS', 'MD', 'MD', 'PhD', 'MD', 'DVM', 'Lee', 'MD', 'DDS', 'MD', 'MD', 'MD', 'MD', 'MD', 'MD', 'DDS', 'Jr.', 'DVM', 'MD', 'MD', 'PhD', 'IV', 'MD', 'DDS', 'DDS', 'DDS', 'MD', 'DDS', 'MD', 'DVM', 'IV', 'MD', 'DDS', 'MD', 'MD', 'DVM', 'Jr.', 'MD', 'PhD', 'II', 'MD', 'DDS', 'DDS', 'DDS', 'Jr.', 'III', 'MD', 'MD', 'MD', 'DDS', 'Jr.', 'DDS', 'DVM', 'DDS', 'DVM', 'MD', 'DDS', 'PhD', 'DDS', 'DDS', 'Jr.', 'Jr.', 'DVM', 'DDS', 'MD', 'MD', 'DVM', 'DDS', 'DVM', 'Jr.', 'MD', 'Jr.', 'MD', 'PhD', 'PhD', 'DDS', 'MD', 'DDS', 'DVM', 'Cox', 'DVM', 'MD', 'Jr.', 'MD', 'DDS', 'MD', 'MD', 'DDS', 'DDS', 'Roy', 'DDS', 'DDS', 'DDS', 'II', 'PhD', 'MD', 'PhD', 'DDS', 'MD', 'DDS', 'Jr.', 'Day', 'DDS', 'MD', 'PhD', 'DDS', 'Jr.', 'DDS', 'MD', 'MD', 'MD', 'MD', 'DDS', 'MD', 'DDS', 'PhD', 'DVM', 'DDS', 'MD', 'MD', 'MD', 'DDS', 'Jr.', 'Jr.', 'DDS', 'Jr.', 'MD', 'MD', 'PhD', 'PhD', 'DDS', 'MD', 'MD', 'III', 'DVM', 'PhD', 'Jr.', 'II', 'DDS', 'DDS', 'DVM', 'MD', 'II', 'MD', 'DDS', 'MD', 'DDS', 'PhD', 'DDS', 'DDS', 'II', 'DVM', 'DDS', 'Jr.', 'DVM', 'MD', 'MD', 'DVM', 'MD', 'DDS', 'DVM', 'DDS', 'MD', 'II', 'PhD', 'MD', 'MD', 'MD', 'DDS', 'MD', 'MD', 'DDS', 'DDS', 'MD', 'DDS', 'PhD', 'DVM', 'DVM', 'MD', 'MD', 'DDS', 'DDS', 'PhD', 'MD', 'IV', 'DDS', 'Jr.', 'DDS', 'Jr.', 'MD', 'MD', 'MD', 'DDS', 'MD', 'DVM', 'DVM', 'DDS', 'DDS', 'Jr.', 'MD', 'MD', 'DDS', 'DDS', 'MD', 'MD', 'MD', 'MD', 'DVM', 'MD', 'DVM', 'DVM', 'MD', 'DDS', 'MD', 'Jr.', 'DDS', 'MD', 'MD', 'DVM', 'Jr.', 'DDS', 'MD', 'MD', 'PhD', 'DDS', 'Jr.', 'MD', 'DDS', 'MD', 'DDS', 'Jr.', 'Jr.', 'DVM', 'MD', 'DDS', 'PhD', 'MD', 'PhD', 'MD', 'V', 'II', 'MD', 'PhD', 'DVM', 'MD', 'MD', 'PhD', 'MD', 'MD', 'MD', 'DDS', 'DVM', 'Jr.', 'MD', 'Jr.', 'Jr.', 'DDS', 'PhD', 'DVM', 'DVM', 'MD', 'MD', 'MD', 'DVM', 'MD', 'DDS', 'MD', 'DDS', 'Jr.', 'MD', 'DDS', 'DDS', 'Jr.', 'DVM', 'DVM', 'DDS', 'MD', 'MD', 'DVM', 'MD', 'MD', 'MD', 'DDS', 'MD', 'Jr.', 'MD', 'MD', 'PhD', 'PhD', 'DDS', 'DDS', 'DDS', 'MD', 'MD', 'PhD', 'Jr.', 'MD', 'DDS', 'III', 'DVM', 'Jr.', 'DDS', 'DDS', 'MD', 'DVM', 'MD', 'DDS', 'MD', 'PhD', 'DDS', 'Lee', 'MD', 'Jr.', 'MD', 'DVM', 'DDS', 'DDS', 'MD', 'MD', 'DVM', 'DVM', 'DVM', 'MD', 'DDS', 'DVM', 'DDS', 'MD', 'MD', 'MD', 'DDS', 'PhD', 'DDS', 'DVM', 'DDS', 'DVM', 'DDS', 'DVM', 'DVM', 'DDS', 'II', 'MD', 'III', 'DDS', 'DDS', 'DVM', 'DVM', 'MD', 'Jr.', 'II', 'MD', 'PhD', 'PhD', 'MD', 'DDS', 'DVM', 'DVM', 'MD', 'MD', 'DVM', 'DVM', 'PhD', 'Jr.', 'Jr.', 'MD', 'MD', 'DDS', 'DDS', 'III', 'PhD', 'Jr.', 'MD', 'MD', 'MD', 'DDS', 'MD', 'DDS', 'MD', 'DVM', 'PhD', 'MD', 'MD', 'PhD', 'Jr.', 'MD', 'MD', 'MD', 'MD', 'MD', 'MD', 'DVM', 'DVM', 'PhD', 'DDS', 'DDS', 'MD', 'DDS', 'MD', 'DVM', 'DVM', 'DDS', 'DVM', 'DDS', 'MD', 'MD', 'DVM', 'DVM', 'DDS', 'Jr.', 'PhD', 'MD', 'DVM', 'DVM', 'DDS', 'DVM', 'MD', 'MD', 'MD', 'II', 'DDS', 'DDS', 'DDS', 'MD', 'Jr.', 'MD', 'Jr.', 'DDS', 'MD', 'MD', 'DVM', 'MD', 'DDS', 'DDS', 'PhD', 'Jr.', 'Jr.', 'Jr.', 'DDS', 'Jr.', 'MD', 'MD', 'DDS', 'MD', 'Jr.', 'MD', 'DDS', 'Jr.', 'DDS', 'MD', 'MD', 'Jr.', 'PhD', 'DDS', 'MD', 'II', 'PhD', 'DVM', 'MD', 'DDS', 'PhD', 'MD', 'MD', 'DDS', 'Jr.', 'MD', 'DVM', 'MD', 'MD', 'MD', 'MD', 'MD', 'DDS', 'DVM', 'PhD', 'DVM', 'III', 'Jr.', 'DVM', 'MD', 'MD', 'V', 'Jr.', 'MD', 'DVM', 'MD', 'DDS', 'DVM', 'DDS', 'Jr.', 'MD', 'PhD', 'DVM', 'DDS', 'PhD', 'MD', 'DDS', 'DDS', 'MD', 'DVM', 'IV', 'Jr.', 'MD', 'MD', 'Jr.', 'PhD', 'II', 'Jr.', 'MD', 'MD', 'MD', 'Jr.', 'MD', 'DVM', 'PhD', 'PhD', 'DDS', 'DDS', 'PhD', 'MD', 'Jr.', 'MD', 'DDS', 'MD', 'DDS', 'DVM', 'DDS', 'DVM', 'MD', 'MD', 'PhD', 'Jr.', 'Jr.', 'MD', 'DDS', 'MD', 'DVM', 'MD', 'DVM', 'DDS', 'PhD', 'PhD', 'Kim', 'DDS', 'PhD', 'DVM', 'PhD', 'DVM', 'DDS', 'MD', 'Jr.', 'PhD', 'MD', 'MD', 'II', 'III', 'MD', 'DDS', 'DDS', 'PhD', 'MD', 'DVM', 'MD', 'DDS', 'MD', 'DDS', 'Jr.', 'DDS', 'DDS', 'MD', 'IV', 'Jr.', 'DDS', 'DDS', 'Jr.', 'DVM', 'DVM', 'DVM', 'DVM', 'MD', 'DVM', 'DDS', 'MD', 'MD', 'DDS', 'DDS', 'DVM', 'III', 'DVM', 'MD', 'DVM', 'DDS', 'MD', 'MD', 'DVM', 'DVM', 'MD', 'III', 'DDS', 'MD', 'DDS', 'DVM', 'Jr.', 'III', 'MD', 'MD', 'PhD', 'DVM', 'DDS', 'MD', 'Jr.', 'DDS', 'MD', 'II', 'MD', 'Jr.', 'DDS', 'PhD', 'DDS', 'DDS', 'II', 'Jr.', 'DDS', 'MD', 'II', 'MD', 'MD', 'MD', 'Jr.', 'DDS', 'MD', 'DVM', 'PhD', 'MD', 'DVM', 'DDS', 'DDS', 'DVM', 'DDS', 'DDS', 'MD', 'MD', 'MD', 'MD', 'DDS', 'DVM', 'PhD', 'DDS', 'DDS', 'MD', 'MD', 'MD', 'DDS', 'DVM', 'MD', 'II', 'MD', 'Jr.', 'Jr.', 'MD', 'MD', 'MD', 'MD', 'DVM', 'MD', 'Jr.', 'PhD', 'PhD', 'PhD', 'DDS', 'Jr.', 'DVM', 'DDS', 'MD', 'DVM', 'PhD', 'MD', 'Jr.', 'Jr.', 'DVM', 'MD', 'DDS', 'MD', 'MD', 'Lee', 'MD', 'MD', 'MD', 'DDS', 'PhD', 'MD', 'PhD', 'MD', 'DVM', 'MD', 'MD', 'MD', 'DDS', 'II', 'DVM', 'Jr.', 'DVM', 'MD', 'Jr.', 'DDS', 'DVM', 'DDS', 'Jr.', 'DVM', 'Jr.', 'DDS', 'MD', 'PhD', 'DDS', 'DDS', 'DVM', 'MD', 'MD', 'PhD', 'DDS', 'DDS', 'DDS', 'DDS', 'MD', 'DVM', 'DVM', 'DVM', 'DDS', 'MD', 'MD', 'MD', 'Jr.', 'PhD', 'MD', 'Jr.', 'DVM', 'DDS', 'DVM', 'MD', 'DVM', 'MD', 'DDS', 'DDS', 'PhD', 'DDS', 'Jr.', 'DDS', 'MD', 'MD', 'MD', 'MD', 'DDS', 'DVM', 'MD', 'MD', 'PhD', 'MD', 'MD', 'II', 'MD', 'Jr.', 'PhD', 'MD', 'PhD', 'MD', 'MD', 'DDS', 'Jr.', 'PhD', 'DDS', 'MD', 'DDS', 'DDS', 'MD', 'MD', 'MD', 'Jr.', 'DDS', 'DDS', 'MD', 'MD', 'MD', 'MD', 'IV', 'Jr.', 'MD', 'DDS', 'MD', 'DDS', 'MD', 'MD', 'Jr.', 'MD', 'DVM', 'DVM', 'DVM', 'MD', 'MD', 'DVM', 'DVM', 'PhD', 'Jr.', 'PhD', 'DVM', 'Jr.', 'MD', 'MD', 'DDS', 'III', 'DVM', 'DDS', 'Jr.', 'MD', 'MD', 'Jr.', 'MD', 'MD', 'DVM', 'Jr.', 'Jr.', 'DDS', 'PhD', 'DDS', 'DDS', 'DDS', 'Jr.', 'Jr.', 'MD', 'DVM', 'DDS', 'MD', 'MD', 'PhD', 'DDS', 'MD', 'DDS', 'DVM', 'DVM', 'MD', 'DDS', 'MD', 'MD', 'MD', 'Jr.', 'MD', 'DVM', 'DDS', 'MD', 'PhD', 'MD', 'II', 'Jr.', 'III', 'MD', 'PhD', 'MD', 'MD', 'PhD', 'II', 'DDS', 'DVM', 'DDS', 'MD', 'DDS', 'MD', 'DVM', 'MD', 'III', 'DDS', 'MD', 'DVM', 'MD', 'II', 'DDS', 'MD', 'MD', 'DDS', 'MD', 'MD', 'DVM', 'MD', 'MD', 'MD', 'II', 'DDS', 'Jr.', 'MD', 'DDS', 'MD', 'MD', 'MD', 'MD', 'DDS', 'IV', 'MD', 'Jr.', 'III', 'DDS', 'DDS', 'MD', 'DDS', 'DVM', 'DVM', 'PhD', 'MD', 'II', 'Li', 'DVM', 'MD', 'DVM', 'DDS', 'DDS', 'DDS', 'DVM', 'MD', 'DVM', 'MD', 'MD', 'MD', 'MD', 'Jr.', 'DVM', 'MD', 'MD', 'MD', 'MD', 'DDS', 'MD', 'PhD', 'DDS', 'MD', 'MD', 'DDS', 'Jr.', 'DDS', 'DDS', 'DVM', 'DDS', 'DDS', 'MD', 'Jr.', 'DDS', 'PhD', 'Jr.', 'DDS']

In [124]:

#isolate prefixes "Miss" is longest at 4 characters. 
prefix_list=[]
for name in fixer_uppers:
    if len(name.split()[0]) <= 4:
        prefix_list.append(name.split()[0])
print(prefix_list)

['Dr.', 'Dr.', 'Mr.', 'Dr.', 'Miss', 'Luke', 'Dr.', 'Mrs.', 'Mrs.', 'Mr.', 'Dr.', 'Mr.', 'Mr.', 'Mary', 'Mrs.', 'Mrs.', 'Mr.', 'Tara', 'Dr.', 'Mr.', 'Mrs.', 'Mr.', 'Mr.', 'John', 'Mr.', 'Mrs.', 'Mr.', 'Dr.', 'Mr.', 'Mr.', 'Dale', 'Dr.', 'Dr.', 'Dr.', 'Ms.', 'Dr.', 'Dr.', 'Mr.', 'Mrs.', 'Amy', 'Mr.', 'Dr.', 'Mr.', 'Mr.', 'Mrs.', 'Mrs.', 'Mr.', 'Lisa', 'Mr.', 'Dr.', 'Mr.', 'Mr.', 'Mr.', 'Dr.', 'Mr.', 'Mark', 'Mrs.', 'Dr.', 'Dr.', 'Miss', 'Mr.', 'Miss', 'Mr.', 'Mrs.', 'Mr.', 'Mrs.', 'Mr.', 'Mr.', 'Mr.', 'Dr.', 'Dr.', 'Miss', 'Mr.', 'Mrs.', 'Mr.', 'Tara', 'Dr.', 'Mr.', 'Cody', 'Mr.', 'Dr.', 'Mr.', 'Ms.', 'Dr.', 'Mr.', 'Mrs.', 'Sara', 'Mr.', 'Mrs.', 'Dr.', 'Mr.', 'Dr.', 'Mr.', 'Mrs.', 'Mr.', 'Mr.', 'Mr.', 'Mr.', 'Mr.', 'Dr.', 'Mrs.', 'Mr.', 'Mrs.', 'Dr.', 'Ryan', 'Mrs.', 'Mr.', 'Ms.', 'Mr.', 'Dr.', 'John', 'Mr.', 'Dr.', 'Dr.', 'Mrs.', 'Dr.', 'Mrs.', 'Mr.', 'Mr.', 'Mrs.', 'Dr.', 'Dr.', 'Miss', 'Miss', 'Mr.', 'Mr.', 'Mr.', 'Dr.', 'Dr.', 'Mrs.', 'Mr.', 'Ms.', 'Mr.', 'Miss', 'Tony', 'Dr.', 'Mr.', 'Mr.', 'Mrs.', 'Mr.', 'Mrs.', 'Miss', 'Mrs.', 'Jodi', 'Mr.', 'Mr.', 'Mrs.', 'Mr.', 'Mr.', 'Mrs.', 'Mrs.', 'Mrs.', 'Mr.', 'Mr.', 'Mr.', 'Mrs.', 'Dr.', 'Mr.', 'Mr.', 'Mrs.', 'Mr.', 'Mrs.', 'Mr.', 'Dr.', 'Mr.', 'Mr.', 'Ruth', 'Dr.', 'Mr.', 'Ms.', 'Dr.', 'Mr.', 'Mrs.', 'Mr.', 'Dr.', 'Dr.', 'John', 'Dr.', 'Mr.', 'Mrs.', 'Mrs.', 'Mrs.', 'Dr.', 'Mrs.', 'John', 'Amy', 'Adam', 'Dr.', 'Eric', 'Mrs.', 'Mr.', 'Mrs.', 'Dr.', 'Dr.', 'Kyle', 'Mr.', 'Ms.', 'Lynn', 'Dr.', 'Mr.', 'Jon', 'Mrs.', 'Mrs.', 'Mrs.', 'Dr.', 'Mrs.', 'Dr.', 'Dr.', 'Dr.', 'Mrs.', 'Mrs.', 'Judy', 'Mr.', 'Dr.', 'Mr.', 'Mrs.', 'Dr.', 'Mr.', 'Mr.', 'Mr.', 'Sara', 'Dr.', 'Dr.', 'Mrs.', 'Tara', 'Dr.', 'Mrs.', 'Dr.', 'Miss', 'Mrs.', 'Mr.', 'Dr.', 'Miss', 'Tina', 'Dr.', 'Eric', 'Ms.', 'Ms.', 'Mr.', 'Mrs.', 'Dr.', 'Dr.', 'Mr.', 'Mr.', 'Dr.', 'Mr.', 'Mr.', 'Dr.', 'Miss', 'Dr.', 'Paul', 'Mrs.', 'Mr.', 'Mrs.', 'Mr.', 'Mr.', 'Mr.', 'Dr.', 'Mrs.', 'Dr.', 'Dr.', 'Mrs.', 'Mrs.', 'Dr.', 'Dr.', 'Dr.', 'Mr.', 'Ms.', 'Dr.', 'Mr.', 'Mrs.', 'Dr.', 'Mrs.', 'Dr.', 'Mrs.', 'Mr.', 'Dr.', 'Mrs.', 'Mrs.', 'Mrs.', 'Dr.', 'Dr.', 'Mr.', 'Mr.', 'Mr.', 'Dr.', 'Marc', 'Mr.', 'Dr.', 'Dr.', 'Dr.', 'Mrs.', 'Dr.', 'Mrs.', 'Mrs.', 'Mr.', 'Mrs.', 'Dr.', 'Dr.', 'Dr.', 'Dr.', 'Mr.', 'Dr.', 'Mr.', 'Mrs.', 'Dr.', 'Dr.', 'Dr.', 'Amy', 'Dr.', 'Mr.', 'Mrs.', 'Mr.', 'Mrs.', 'Dr.', 'Dr.', 'Mr.', 'Mrs.', 'Dr.', 'Jill', 'Mary', 'Carl', 'Mr.', 'Dr.', 'Jose', 'Mrs.', 'Mary', 'Ms.', 'Jose', 'Lisa', 'Mrs.', 'Mr.', 'Miss', 'Mr.', 'Eric', 'Mr.', 'Mrs.', 'Mrs.', 'Miss', 'Emma', 'Mrs.', 'Dr.', 'Mrs.', 'Mr.', 'Dr.', 'Mr.', 'Mr.', 'Dr.', 'Dr.', 'Mrs.', 'Dr.', 'Dr.', 'Mr.', 'Mr.', 'Ms.', 'Mr.', 'Gary', 'Mr.', 'Lori', 'Mrs.', 'Mr.', 'Mr.', 'Mrs.', 'Mrs.', 'Noah', 'Dawn', 'Dr.', 'Mr.', 'Mr.', 'Mrs.', 'Mrs.', 'Mrs.', 'Dr.', 'Chad', 'Mr.', 'Paul', 'Mrs.', 'Dr.', 'Mrs.', 'Mrs.', 'Mrs.', 'Dr.', 'Dr.', 'Mrs.', 'Mrs.', 'Dr.', 'Miss', 'Mrs.', 'Eric', 'Dr.', 'Mrs.', 'Dr.', 'Mr.', 'Dr.', 'Adam', 'Mr.', 'Dr.', 'Dr.', 'Mr.', 'Mr.', 'Mr.', 'Mr.', 'Anne', 'Mr.', 'Mrs.', 'Troy', 'Mr.', 'Mrs.', 'Dr.', 'Mr.', 'Mr.', 'Mr.', 'Mr.', 'Miss', 'Mr.', 'Anna', 'John', 'Mr.', 'Mr.', 'Mrs.', 'Eric', 'Mr.', 'Dr.', 'Dr.', 'Mr.', 'Mr.', 'Ryan', 'Mrs.', 'Dr.', 'Emma', 'Mr.', 'Mr.', 'Mrs.', 'Miss', 'Mr.', 'Mr.', 'Mrs.', 'Mrs.', 'Mr.', 'Mr.', 'Mr.', 'Mrs.', 'Mr.', 'Dr.', 'Lisa', 'Mr.', 'Dr.', 'Mrs.', 'John', 'Mrs.', 'Ms.', 'Mrs.', 'Mrs.', 'Dr.', 'Mr.', 'Mrs.', 'Mr.', 'Amy', 'Dr.', 'Mr.', 'Dr.', 'Mrs.', 'Dr.', 'Dr.', 'Lori', 'Mr.', 'Dr.', 'Mrs.', 'Amy', 'Dr.', 'Mrs.', 'Dr.', 'Anne', 'Dr.', 'Mr.', 'Mr.', 'Mr.', 'Mr.', 'Mr.', 'Mrs.', 'Mike', 'Mrs.', 'Todd', 'Mrs.', 'Mr.', 'Mr.', 'Mrs.', 'Dr.', 'Mr.', 'Mrs.', 'Dr.', 'Dr.', 'Mrs.', 'Mrs.', 'Mr.', 'Dr.', 'Mrs.', 'Mrs.', 'Dr.', 'Dr.', 'Miss', 'Mr.', 'Mrs.', 'Dr.', 'Dr.', 'Mrs.', 'Mr.', 'Mrs.', 'Mr.', 'Mr.', 'Dr.', 'Mr.', 'Dr.', 'Mrs.', 'Dr.', 'Ms.', 'Mr.', 'Miss', 'Dr.', 'Miss', 'Dr.', 'Leah', 'Miss', 'Mr.', 'Mr.', 'Dr.', 'Mr.', 'Dr.', 'Dr.', 'Dr.', 'Mr.', 'Dr.', 'Dr.', 'Dr.', 'Mr.', 'Dr.', 'Ian', 'Dr.', 'Mr.', 'Dr.', 'Mr.', 'Dr.', 'Mrs.', 'Miss', 'Dr.', 'Mrs.', 'Ms.', 'Dr.', 'Dr.', 'Mark', 'Mr.', 'Kari', 'Mrs.', 'Mrs.', 'Mr.', 'Mrs.', 'Dr.', 'Dr.', 'Mrs.', 'Dr.', 'Mrs.', 'Kara', 'Mark', 'John', 'Mrs.', 'Dr.', 'Mrs.', 'Mr.', 'Eric', 'John', 'Dr.', 'Mrs.', 'Dr.', 'Mr.', 'Paul', 'Dr.', 'Mrs.', 'Dr.', 'Dr.', 'Dr.', 'Adam', 'Mrs.', 'Ms.', 'Dr.', 'Mrs.', 'Dr.', 'Ms.', 'Mrs.', 'Mr.', 'Mr.', 'Mrs.', 'Dr.', 'Mrs.', 'Mr.', 'Dr.', 'Mr.', 'Dr.', 'Dr.', 'Paul', 'Mrs.', 'Cory', 'Mrs.', 'Dr.', 'Dr.', 'Dr.', 'Mr.', 'Mr.', 'Erin', 'Dr.', 'Dr.', 'Ms.', 'Mrs.', 'Mr.', 'Miss', 'Mr.', 'Mr.', 'Mr.', 'Ms.', 'Mrs.', 'Mr.', 'Mrs.', 'Miss', 'Ms.', 'Dr.', 'Dr.', 'Mrs.', 'Mr.', 'Mrs.', 'John', 'Lisa', 'Mr.', 'Mr.', 'Mrs.', 'Mr.', 'Jon', 'Mrs.', 'Dr.', 'Greg', 'Ms.', 'Mrs.', 'Mr.', 'Mrs.', 'Miss', 'Mr.', 'Dr.', 'Joe', 'Dr.', 'Mark', 'Dr.', 'Mrs.', 'Miss', 'Mr.', 'Mr.', 'Mr.', 'Mrs.', 'Dr.', 'Mr.', 'Mr.', 'Mr.', 'Adam', 'Mr.', 'Mr.', 'Dana', 'Dr.', 'Mr.', 'Dr.', 'Mrs.', 'Mr.', 'Erik', 'Mrs.', 'Dr.', 'Miss', 'Mrs.', 'Ms.', 'Mr.', 'Mr.', 'Mr.', 'John', 'Gail', 'Todd', 'Mr.', 'Mr.', 'Mrs.', 'Ms.', 'Ryan', 'Mrs.', 'Mrs.', 'Dr.', 'Erik', 'Omar', 'Mr.', 'Dr.', 'Cody', 'Ms.', 'Dr.', 'Mrs.', 'Dr.', 'Mr.', 'Mr.', 'Miss', 'Mark', 'Dr.', 'Dr.', 'Mr.', 'Mrs.', 'Mr.', 'Mr.', 'Mr.', 'Mrs.', 'Mr.', 'Mrs.', 'Mr.', 'Dr.', 'Dr.', 'Mr.', 'Mr.', 'Mr.', 'Dr.', 'Miss', 'Mrs.', 'Seth', 'Dr.', 'Mrs.', 'Ryan', 'Mrs.', 'Mrs.', 'Mrs.', 'Mr.', 'Mrs.', 'Dr.', 'Mr.', 'Mrs.', 'Ryan', 'Mrs.', 'Mr.', 'Dr.', 'Dr.', 'Mr.', 'Dr.', 'Dr.', 'Mrs.', 'Ms.', 'Dr.', 'Dr.', 'Mr.', 'Mr.', 'Ms.', 'Dr.', 'Dr.', 'Dr.', 'Mr.', 'Mrs.', 'Mr.', 'Lisa', 'Mr.', 'Dr.', 'Chad', 'Gina', 'Dr.', 'Mr.', 'Mr.', 'Mrs.', 'Amy', 'Mr.', 'Mrs.', 'Mr.', 'Dr.', 'Mr.', 'Dr.', 'Mrs.', 'Lisa', 'Mrs.', 'Dr.', 'Miss', 'Mr.', 'Mr.', 'Ms.', 'Mrs.', 'Mr.', 'Mrs.', 'Mr.', 'Dr.', 'Dr.', 'Mr.', 'Lisa', 'Dr.', 'Mr.', 'Ms.', 'Mrs.', 'Mr.', 'Dr.', 'Dr.', 'Mrs.', 'Sean', 'Dr.', 'Dr.', 'Mr.', 'Mr.', 'Miss', 'Miss', 'Dr.', 'Mr.', 'Dr.', 'Dr.', 'Mrs.', 'Mr.', 'Mrs.', 'Mrs.', 'Dr.', 'Mrs.', 'Dr.', 'Mr.', 'Mrs.', 'Mr.', 'Mr.', 'Todd', 'Dr.', 'Mrs.', 'Mrs.', 'Miss', 'Dr.', 'Mrs.', 'Mr.', 'Mr.', 'Mrs.', 'Adam', 'Mrs.', 'Ms.', 'Tony', 'Dr.', 'Miss', 'Toni', 'Ms.', 'Mr.', 'Mr.', 'Dr.', 'Ms.', 'Dr.', 'Mrs.', 'Dr.', 'Dr.', 'Dr.', 'Jose', 'Dr.', 'Dr.', 'Amy', 'John', 'Mrs.', 'Mr.', 'Mrs.', 'Mrs.', 'Miss', 'Mr.', 'Dr.', 'Mary', 'Mark', 'Dr.', 'Ms.', 'Ms.', 'Dr.', 'Mr.', 'Dr.', 'Miss', 'Mr.', 'Dr.', 'Troy', 'John', 'Dr.', 'Kim', 'Mr.', 'Mr.', 'Miss', 'Mary', 'Mrs.', 'Mrs.', 'Mrs.', 'Mr.', 'Dr.', 'Ms.', 'Mrs.', 'Anna', 'Mr.', 'Mrs.', 'Mr.', 'Mr.', 'Dr.', 'Mrs.', 'Dr.', 'Dr.']

In [125]:
#create a set of unique items to isolate what we need to delete

set(suffix_list)

{'Cox',
 'DDS',
 'DVM',
 'Day',
 'II',
 'III',
 'IV',
 'Jr.',
 'Kim',
 'Lee',
 'Li',
 'MD',
 'PhD',
 'Roy',
 'V'}

In [126]:
set(prefix_list)

{'Adam',
 'Amy',
 'Anna',
 'Anne',
 'Carl',
 'Chad',
 'Cody',
 'Cory',
 'Dale',
 'Dana',
 'Dawn',
 'Dr.',
 'Emma',
 'Eric',
 'Erik',
 'Erin',
 'Gail',
 'Gary',
 'Gina',
 'Greg',
 'Ian',
 'Jill',
 'Jodi',
 'Joe',
 'John',
 'Jon',
 'Jose',
 'Judy',
 'Kara',
 'Kari',
 'Kim',
 'Kyle',
 'Leah',
 'Lisa',
 'Lori',
 'Luke',
 'Lynn',
 'Marc',
 'Mark',
 'Mary',
 'Mike',
 'Miss',
 'Mr.',
 'Mrs.',
 'Ms.',
 'Noah',
 'Omar',
 'Paul',
 'Ruth',
 'Ryan',
 'Sara',
 'Sean',
 'Seth',
 'Tara',
 'Tina',
 'Todd',
 'Toni',
 'Tony',
 'Troy'}

In [127]:
#get rid of: 'Dr.', 'Mr.', 'Ms.', 'Miss', 'MD', 'DDS', 'DVM', 'Ph.D.' from original list of student names along with the white space ""

In [140]:
remove=['Dr. ', 'Mr. ', 'Ms. ', 'Miss ', 'MD', 'DDS', 'DVM', 'Ph.D.']
for x in remove:
    df['student_name']=df['student_name'].str.replace(x, "")
#validate
# print(df['student_name'].tolist())
fixed_names=df['student_name'].tolist()
print(fixed_names)

ie Pham', 'Keith Smith', 'Steven Holmes', 'Ashley Mendez', 'Jermaine White', 'Paul Torres', 'Jill Sanchez', 'Denise Sherman', 'Timothy Benson', 'Katherine Anderson', 'Sara Robinson', 'Donna Phillips', 'Preston Ortiz', 'Jacob Vazquez', 'Gary Santiago', 'Theresa Sparks', 'Matthew Rodriguez', 'Amber Hood', 'Robert Wilkinson', 'Jade Black', 'Amy Kirby', 'Amanda Fields', 'Caroline Smith', 'Michael Knight', 'Hunter Garcia', 'Samantha Stone', 'Christian Smith', 'Victoria Mullen', 'Julie Alvarez', 'Chris Bennett', 'Jeffrey Hudson', 'Anthony Bell', 'Angela Rodriguez', 'Suzanne Odonnell', 'James Esparza', 'Crystal Hodge', 'Kimberly Ramos', 'Melissa Payne', 'Alicia Thompson', 'Holly Coleman', 'Vanessa Parker', 'Megan Campbell', 'Steve Cardenas', 'Patricia Lewis', 'Paul Paul', 'Bryan Simmons', 'Alice Carson', 'April Ellison', 'Danielle Jensen', 'Denise Thompson', 'Thomas Phillips', 'Michael Jackson', 'Brianna Martin', 'William Patterson', 'Rachel Hill', 'Marissa Martinez', 'Lisa Ramos', 'Daniel Franklin', 'Alan Harmon', 'Rachel Smith', 'Thomas Meyer ', 'Alejandro Gould', 'Troy Foster ', 'Kevin Smith', 'Jordan Jones', 'Kyle Sanchez', 'Jeremy Aguilar', 'Daniel Galvan', 'Jennifer Rogers', 'Kristie Duffy', 'Blake Pope', 'Sarah Chapman', 'Donald Miller', 'Brittney Bates', 'Edward Howard', 'Jennifer Wilson', 'Courtney Turner', 'Cynthia Mcbride', 'Stephen Cruz', 'William Ellis', 'Stephanie Nguyen', 'Michael Walters', 'Wendy Douglas', 'John Hernandez ', 'Miranda Brown', 'George Hobbs', 'Valerie Krueger ', 'Ashley Strickland', 'Amanda Johnson', 'Carol Valdez ', 'Kyle Macdonald', 'Misty Anderson', 'William Jordan', 'William Potts', 'Jay Johnson ', 'Kristina Mason', 'Kimberly Conway', 'Rebecca Jones', 'Gina Hernandez', 'Holly Moreno', 'Brenda Holloway ', 'Nicholas Mclean', 'Jordan Maxwell', 'Erin Mcguire', 'Ricky Henry', 'Adam Lynch', 'David Gutierrez', 'David Armstrong', 'Brandon Tapia', 'Isabel Bradford', 'Phillip Beasley', 'Aimee Olsen', 'Brian Sullivan', 'Mary Pace', 'Laura Gonzalez', 'Randy Walker', 'Sarah Cohen', 'Donald Martinez', 'Wanda Hall', 'Glenn Howe', 'Brian Bell', 'Shelby Patrick', 'Anthony Castro', 'Blake Horn', 'Jessica Kidd', 'Christie Jones', 'Michael Franco', 'Christopher Jones', 'Ashley Brown', 'William Wolf', 'Mary Hawkins', 'Colton Le', 'Jessica Oconnor', 'David Wu', 'William Parsons', 'Ricky Perez', 'Jeffrey Anderson', 'Thomas Perez', 'Lucas Cox', 'Aaron Perez', 'Wendy Parker ', 'George Bailey', 'Richard Mullins', 'Andre Ramirez', 'Margaret Brown', 'Ryan Munoz', 'Sharon Barker', 'Benjamin Singleton', 'Megan Soto', 'Jillian Ashley', 'Maria Foster', 'Riley Horn', 'Andrew Daniels', 'Madison Castaneda', 'Krystal Reid', 'Stephanie Rogers', 'Chad Hurley', 'Dwayne Soto', 'Jennifer Cohen', 'Kathy Lee', 'Claudia Johnston', 'Stephanie Bailey', 'Kevin Mejia', 'Robert Aguilar', 'Beverly Cox', 'Carly Andrews', 'Michelle Morris', 'Timothy Melendez', 'Regina Reeves', 'Crystal Goodwin', 'Alison Hunter', 'Kayla Anderson', 'Kara Spears', 'Michelle Peterson', 'Joseph Pace', 'Phillip Thomas', 'Teresa Smith', 'Kim Smith ', 'Nathan Robinson', 'David Cox', 'Lauren Barton', 'Joshua Little', 'Marie Miller', 'Richard Miller', 'Carolyn Stewart', 'Andrew Burgess', 'Sarah Smith', 'James Aguilar', 'Tammy Larson', 'Janet Roth', 'Karen Ellis', 'Suzanne Anderson', 'Breanna Aguilar', 'Andrew Dickerson', 'Kathleen Patrick', 'Johnny Matthews', 'Valerie Woods', 'Tamara Watkins', 'Lisa Carlson', 'David Becker', 'Nathaniel Wood', 'Eric Barton', 'Brianna Lynn', 'Emily James', 'Jeremy Hernandez', 'Traci White', 'Emma Palmer', 'Christine Garcia', 'Kimberly Bond', 'Darrell Oconnell', 'Anthony Page', 'Richard Prince', 'Vicki Miller', 'Teresa Stevenson', 'Renee Gill', 'Robert Moore', 'Lisa Moore', 'Marcus Romero', 'Crystal Oliver', 'Carrie Mora', 'Kevin Stewart', 'Lauren Daniels', 'Christina Rivera', 'Robin Perez', 'Terry Anderson', 'Lisa Brown', 'Kristi Wells', 'Megan Robertson', 'Collin Harvey', 'Edward Anderson', 'Amanda Morales', 'Daniel Brown', 'Scott Johnson', 'Nicole Rowe', 'Patricia Sanders', 'Christopher Perry', 'Mark Nichols', 'Joseph Ross', 'Nathaniel Owens', 'Kristi Sanchez', 'Jennifer Hunt', 'Lisa Burton', 'Kristen Garcia', 'Erica Watkins', 'Elizabeth Cook', 'Ryan Romero', 'Michael Bray', 'Ann Taylor', 'Timothy Johnson', 'Victor Sharp', 'Stacy Oconnell', 'Jacqueline Green', 'Edward Solomon', 'Christine Lyons', 'Jordan Mueller', 'Jessica Wade', 'Hannah Hudson', 'Dorothy Cervantes', 'Cassandra Evans', 'Anthony Woods', 'Olivia Pratt', 'Kenneth Baker', 'John Boyd', 'Jesse Wilson', 'Jesse Gilbert', 'David Turner', 'Richard Thomas', 'Paul Thompson', 'Cody Thompson', 'Lindsey Ortiz', 'Charles Holland', 'Michelle Kelly', 'Kristina Arias', 'Ryan Gonzalez', 'Wayne Shepherd', 'Matthew Campbell', 'Yolanda Brooks', 'Timothy Gray', 'Brett Chambers', 'Curtis Parker', 'Hector Romero', 'Norman Moreno', 'Michael Hoffman', 'Natalie Gardner', 'Diane Ray', 'Pam Ellis', 'Stephanie Sandoval', 'Laura Ramos', 'Danielle Acosta', 'Terri Guerra', 'Frank Ramirez', 'Jessica Williams', 'Tina Greer', 'Melissa Martin', 'Kristy Harris', 'Larry Weber', 'Anna Lewis', 'Wesley Fields ', 'Aaron Holmes', 'Michael Vasquez', 'Marc Snyder', 'Thomas Tyler', 'James Harrison', 'David Saunders', 'Nathaniel Carr', 'Adam Maxwell', 'Eric Williams', 'Chelsea Castillo', 'Jaime Sloan', 'Sarah Rodriguez', 'Kristina Schaefer', 'Diane Martin', 'Clinton Blake', 'Savannah Smith', 'Heather Hunter', 'Lisa Tucker', 'Renee Moore', 'Nicole White ', 'Keith King', 'Amanda Skinner ', 'Marcus Wallace', 'James Horton', 'Darrell Simpson', 'Diane Rush', 'Christine Guerrero', 'Rita Perez', 'Sarah Williams', 'Jason Key', 'Christine Smith', 'Jennifer Dixon', 'Timothy Wilson', 'Maxwell Anderson', 'Christina Robinson', 'Abigail Durham', 'Charlotte Graham', 'Tanya Barnes', 'Theresa Gentry', 'Donald Nicholson', 'Nathan Smith', 'Sarah Briggs', 'Joshua Thomas', 'Alexander Wilson', 'David Smith', 'Rebecca Reilly', 'Paul Bowers', 'Teresa Chapman', 'Kimberly Case', 'Guy Goodwin', 'Brenda Rivera', 'Gregory Shepherd', 'Kenneth Simon', 'James Stone', 'Scott Smith', 'Kevin Costa', 'Kayla Williams', 'Joshua Burch', 'Emily Washington', 'Elizabeth Graham', 'Kristy Perry', 'Stacey Rodriguez', 'Brittany Harper', 'Robert Pollard', 'Heidi Gomez', 'Mark White', 'Dustin Meyer', 'Stephanie Pham', 'Jeffery Howard', 'Christina Owen', 'Ana Ellis', 'Evan Jones', 'William Schmidt', 'Elizabeth Johnson', 'Ronald Yates', 'Kenneth Collins', 'Stacey Jennings', 'Brandy Cox', 'Ann Garcia', 'David Young', 'Steven Thompson', 'Kaitlyn Davis', 'Patricia Maddox', 'Dylan Ray', 'Sharon Larson', 'Marc Short', 'John Atkins', 'Eugene Johnson', 'Terry Torres', 'Eric Huff', 'Joseph Kim', 'Katie Neal', 'Amy Vega', 'Daniel Wilson', 'Kurt Martinez', 'Dennis Rodriguez', 'Elaine Stephens', 'Melissa Graves', 'Adrienne Turner ', 'Sandra Franco', 'Adam Woods', 'Patrick Joyce', 'Tanya Chen', 'Tracy Dawson', 'Lisa Coleman', 'Brenda Lloyd', 'Brianna Frey', 'Michael Green', 'Megan Page', 'Jordan Long', 'Tracy Lewis', 'Christine Sellers', 'Angela Berger', 'Donald Evans', 'Scott Rowe', 'Veronica Drake', 'David Cohen', 'Mark Rice', 'Jesse Reyes', 'Nicole Ritter', 'Lisa Gentry', 'Terry Scott Jr.', 'Cesar Rodriguez ', 'Jennifer Gay ', 'David House', 'Michael Moore', 'Jared Woodward', 'Ashley Black', 'Adam Hinton', 'Rebecca Sanchez', 'Daniel Harris', 'Angie Vance', 'Zachary Davis', 'Joshua Glass', 'Scott Mack', 'Diane Morse', 'Lori Jenkins', 'Paul Garcia', 'Jonathan Dunn', 'Dustin Butler', 'Cody Cortez', 'Bridget Benitez', 'Earl Thompson', 'Tracie Stewart', 'Brenda Le', 'Jennifer Combs', 'Elizabeth Stout', 'Edward Lopez', 'Timothy Baird', 'Drew Jones', 'Kevin Gordon', 'Andrew Anthony', 'David Garner', 'Dawn Richards', 'Zachary Sanchez', 'Paul Butler', 'Heidi Rhodes', 'Kimberly Duncan', 'Andrew Jones', 'Scott Walters', 'Travis Johnson', 'Taylor Owen', 'Ryan Reed', 'Erin Miller', 'Tiffany Alvarez', 'Donna Ramirez', 'David Taylor', 'Jacob Roberts', 'John Small', 'Robert Lloyd', 'Joe Ewing', 'William Carter', 'Melinda Thomas', 'Jill Mckinney', 'John Dunn', 'Jordan Martinez', 'Mary Nixon ', 'Kristin Taylor', 'Ashley Jimenez', 'Jessica Hill', 'Laurie Fowler', 'Michael Johnson', 'Kevin Foster', 'Michael Stevens', 'Tracy Noble', 'Daniel Schultz', 'Bridget Robles', 'Erin Mccann', 'Paul Hayes', 'Glenn Mercer', 'Charles Flores', 'Melissa Wilson', 'Tim Harris', 'John Stuart', 'Kim Williams', 'Andrew Gomez', 'Beverly Whitney', 'Eric Cox', 'Leslie Kelly ', 'Eric Kelley', 'Olivia Hernandez', 'Patrick Garcia', 'Teresa Schultz', 'Kim Peck', 'Laura Murphy', 'George Green', 'Richard Bowman', 'Jasmine Garcia', 'Victoria Harrell', 'Julie Nelson', 'Mrs. Kristen Gonzalez', 'Michael Carter ', 'Arthur Martinez', 'James Cruz', 'Brian Monroe', 'Michael Booth', 'Daniel Simpson', 'Kenneth Smith', 'Joseph Mitchell', 'Allen Payne', 'Lisa Ward', 'Teresa Miller', 'Daniel Wallace', 'Sheena Hill', 'Sarah Scott', 'Michael James', 'Angela Thompson', 'Lindsay Ortiz', 'Catherine Wilson', 'Jill Kim', 'Lauren Wilson', 'Stacey Lee', 'Carmen Kim', 'Jennifer Weaver', 'Kristi Castillo', 'Matthew Perez', 'Diana Mcdaniel', 'Julia King', 'Susan Thomas', 'Lisa Price', 'Nancy Hopkins', 'Danny Miller', 'Paul Ewing', 'Frank Davis', 'Jeffrey Schultz', 'Misty Nguyen', 'Leroy Shaffer', 'Raymond Hawkins', 'Robert Lewis', 'Anna Jacobs', 'Nathan Adams', 'Christy Ryan', 'Madison Palmer', 'Christina Hall', 'Charles Dickson', 'Pamela Thompson', 'Meghan Williams', 'Gerald Jones', 'Tara Simpson', 'Ryan Fernandez', 'Marissa Wilson', 'Heather Leblanc', 'Andrea Lee', 'Erica Singh', 'Matthew Crane', 'Jennifer Weaver', 'Brian Thomas', 'Elizabeth Lamb', 'Dakota Marshall', 'Kelly Donaldson', 'Donald Scott', 'Mark Smith', 'Todd Johnson', 'Robin Mathis', 'Carlos Gutierrez', 'Katherine Porter', 'Denise Perry', 'Andrew Nelson', 'Michael Hartman', 'Andrea Sanchez', 'Ronnie Powell', 'Matthew Davis', 'Kristina Morrison', 'Kevin Pierce', 'Frank Mitchell', 'Tony Hoover', 'Jessica Roach', 'Danielle Rodriguez', 'Tracy Nguyen', 'Kelly Bridges', 'Joseph Mcgrath', 'Austin Wilcox', 'Katherine Sims', 'Mary Miller', 'Martin Taylor', 'Madison Suarez', 'Betty Campbell', 'Anna Jackson', 'Anthony Reynolds', 'Joseph Perez ', 'Matthew Dougherty', 'Angela Hill', 'Stephanie Long', 'Kathy Gonzales', 'Kayla Myers', 'Edward Jones', 'Tiffany Cook', 'Bradley Miller', 'Lisa Blackburn', 'Sara Williams', 'Gregory Howell', 'Sarah Allen', 'Russell Schmitt', 'Peter Stone', 'Gerald Estes', 'Holly Moore', 'Allison Webb', 'Steven Reynolds', 'Mrs. Alice Warren', 'Nichole Perez', 'Autumn Green', 'Eileen Rios', 'Jennifer Cooper', 'Martha Molina', 'Judith Potter', 'Evan Martin', 'Heather Bailey', 'Thomas Clark', 'Brian Arnold', 'Julia Kelley ', 'Evan Mitchell', 'Susan Roberts', 'Shannon Lopez', 'James Williams', 'Allison Kerr', 'Tiffany Mccarthy', 'Christina Moreno', 'Tony Byrd', 'Jared Mcdonald', 'Zoe Allen', 'Laura Baker', 'James Hale', 'Timothy Obrien', 'Mariah Proctor', 'Mary Rogers', 'Amber Thompson', 'Yolanda Ochoa', 'Debra Rosales', 'Joseph Wood', 'Andre Fisher', 'David Coffey PhD', 'Kelly Hernandez', 'Cheryl Diaz', 'Linda Chambers', 'William Sandoval', 'Kristen Crawford', 'Erica King', 'Eric Carson', 'James Cruz', 'Nathan Maldonado', 'David Rodriguez', 'Justin Williams', 'Jason Shaw', 'Mrs. Pam Wolf ', 'Catherine Cross', 'Melissa Johnson', 'Lori Wilkerson', 'Katherine Hardin', 'Kevin Vasquez', 'Stephanie Franklin', 'Edward Parrish', 'Caitlin Williams', 'Mark Sanchez', 'Lindsey Benson', 'Rachel Miller', 'Andrea Mack', 'Sarah Brown', 'Lisa Fitzgerald', 'Jessica Prince', 'Jeffery King', 'Travis Spencer', 'Erica Tucker', 'Lauren Casey', 'Emily Williams', 'Kevin Thomas', 'Amanda Small', 'Kerri Torres', 'Danny Powers', 'Jessica Cohen', 'Jeffrey Duarte', 'Crystal Fields', 'Henry Tucker', 'Kenneth Carter', 'Courtney Miller', 'Eric Benson', 'Joshua Vargas', 'Rebekah Perkins', 'Ryan Thomas', 'Pamela Brooks', 'Bridget Shah', 'Cassidy Carter', 'Kelly Michael', 'Michael Flores', 'Robert Wilcox', 'Christopher Melton', 'Stephanie Johnson', 'Thomas Payne', 'Elizabeth Miller', 'Pamela Thomas', 'Victoria Nguyen', 'Brian Mills', 'Deborah Holloway', 'David Gray', 'Kathleen Lewis', 'Michelle Pratt', 'Steven Brown', 'James Wallace', 'Amy Hayes', 'Matthew Nunez', 'Joseph Gentry', 'Heidi Johnson', 'Nancy Harris', 'Ashley Hill', 'Jeffery Abbott', 'Gregory Morgan ', 'Daniel Herrera', 'Pamela Salinas', 'Sarah Johnson', 'Jason Gonzalez', 'Richard Alexander', 'Randy Richards', 'Adriana Reyes', 'Carrie Meyer', 'Phillip Lin', 'Daniel Mack', 'Kimberly Roach', 'Dakota Barry', 'Latoya Graham', 'Manuel Lane', 'Kathy Jones', 'Charles Petty', 'Brent Matthews', 'Amy Lucas', 'Christopher Black', 'Alyssa Burns', 'Jeffrey Evans', 'Carol Williams', 'Kelly Chambers', 'Kayla Anderson', 'Andrew Ellis', 'Michelle Cook', 'Victoria Martin', 'Joshua Underwood', 'Matthew Howard', 'Michelle Gray', 'Rebecca Gonzales', 'James Schmidt', 'Mrs. Samantha Glover', 'Theresa Nelson', 'Raymond Jackson', 'Yvette Ashley', 'David Moss', 'Elizabeth Howard', 'Shelby George', 'Justin Frazier', 'Chelsea Adams', 'Erika Payne', 'Anna Decker ', 'Linda Mccann', 'Leslie Fowler', 'Robin Morris', 'Samuel Campbell', 'Angela Pennington', 'Andrew Stephenson', 'Sandra Mcbride', 'Hailey Lopez ', 'Walter Stokes', 'Dave Diaz', 'Robert Coleman', 'Andrew Gibson', 'Kristina Snow', 'Michael Martinez', 'Patrick Jenkins', 'Larry Scott', 'Dana Kidd', 'Amber Lewis', 'Alan Simmons', 'Rebecca Joseph', 'Brian Acosta', 'Kimberly Erickson', 'Cynthia Maldonado', 'Anthony Flores', 'Jacob Mills', 'James Baker', 'Cynthia Martin', 'Natalie Taylor', 'Ashley Mcdonald', 'Kirk Vaughn', 'Dustin Ray', 'Gabriel Miller', 'Deborah Griffith', 'Christopher Rose', 'Maria Kirk', 'Nancy Fox', 'Heather Davis', 'Taylor Smith', 'Mrs. Amber Gonzalez', 'Leslie Nelson', 'John Escobar', 'Robert Harper', 'Angela Mooney', 'Chad Dudley', 'Richard Lee', 'Elizabeth Ross', 'Cheryl Garner', 'Debbie Garrison', 'Nicole Shaw', 'Kayla Jones', 'Cristina Drake', 'Jason Patel Jr.', 'Tina Salazar', 'Timothy Ward', 'Jeremiah Arroyo', 'Ryan Barnes', 'Jennifer Robinson', 'Matthew Walsh', 'Marissa Reed', 'Matthew Ritter', 'Jennifer Kelley', 'David Silva', 'Reginald Johnson', 'Logan White', 'Cheryl Reynolds', 'Kelly Mclean', 'Laura Richardson', 'Maria Davis', 'Amy Anderson', 'Timothy Smith', 'Laura Kidd', 'Lydia Gomez', 'Stephanie Walker ', 'Joseph Daniels', 'Tracey Hernandez', 'Barry Bridges', 'David Lin', 'Ariel Reynolds', 'Timothy Scott', 'Jonathan Crawford', 'Natalie Dunn', 'Shawn Williams', 'Jennifer Parsons', 'Adam Haley', 'Mary Berry', 'Amy Payne', 'Emily Neal', 'Ashlee Cooley', 'Kenneth Lane', 'Joseph Garcia', 'Michael Sullivan ', 'Christopher Henderson', 'Javier Zamora', 'Theresa Oconnor', 'Jamie Campbell', 'Paige Bates', 'Kelly Lane', 'Steven Hernandez', 'Kristen Sims', 'Todd Fields', 'Larry Holmes', 'Michael Miller', 'Doris Taylor', 'Margaret Hodge', 'Vanessa Burton', 'Debra Thomas', 'Donna Ellison', 'Mrs. Brittney Schultz ', 'Sean Morrison', 'Dillon Davidson', 'Timothy Conner', 'Catherine Romero', 'Michael Williams', 'Susan Greer', 'John Bentley', 'Craig Wells', 'Aaron Martin', 'Alexandra Wright', 'Elizabeth Mccoy', 'Steven Johnson', 'Donna Morales', 'Sean Morales', 'Ashley Park', 'Kristy Ruiz', 'Jason Fisher', 'Gloria Hamilton', 'Evan Moreno', 'Betty Jackson', 'Courtney Santos', 'Lisa Jackson', 'Keith Petty', 'Randy Travis', 'Michael Morgan', 'Stephen Miller', 'Brian Burton', 'Debra Williams', 'Frances Romero', 'Edgar Garcia', 'Eric Williams', 'Louis Elliott', 'Robin Jones', 'Lynn Duncan', 'Anthony Nunez', 'William Newman', 'Taylor Salinas', 'Lauren Kelly', 'Jordan Hamilton', 'Joel Curry', 'Andres Reyes', 'Thomas Pham', 'Gregory Graham', 'Nicholas White', 'Kevin Rowe', 'Michael Palmer', 'Jim Carrillo', 'Katherine Russell', 'Spencer Johnson', 'Mary Taylor', 'Henry Burke', 'Kelly Weaver', 'Christopher Johnson', 'Janice Martin', 'Taylor Cooke', 'Chad Medina', 'Ashley Romero', 'Samantha Steele', 'Stacey Taylor', 'Vicki Meyer', 'Taylor Thomas', 'Peggy King', 'Alexandra Williams', 'Sandra Griffin', 'Yolanda Le', 'Dennis Bradford', 'Ann Duffy', 'Rachel Butler', 'Robert Smith', 'Melissa Hooper', 'Amber Anderson', 'George Collins', 'Robert Reid', 'Stephen Jones', 'Brenda Taylor', 'Denise Foster', 'Alexandria Carpenter', 'Luke Brown', 'Michael Clements', 'Tiffany Francis', 'Shannon Carson', 'Tracey Liu', 'Logan Osborn', 'John Roberson', 'Dennis Anderson', 'Kelly Diaz', 'Chad Carr', 'John Bailey', 'Dennis Peters', 'Laura Bennett ', 'Charles Brown', 'Marissa Richardson', 'Amy Davis', 'Andrea Johnson', 'Jessica Brewer', 'Ashley Lynch', 'Christine Howell', 'Luis Cannon', 'Jennifer Phillips', 'Maria Davis', 'Thomas Anderson', 'Annette Davis', 'David Price', 'Christina Carter', 'Laura Smith', 'Stacey Mitchell', 'Michelle Davis', 'Shane Lindsey', 'Denise Moore', 'Kendra Flynn', 'Austin Burke', 'David Chapman', 'Malik Thomas', 'Cynthia Lloyd', 'Theresa Ryan', 'Amber Reynolds', 'Allen Goodwin ', 'Terry Diaz', 'Jeffrey Davis', 'Diana Jones', 'Mia Gould', 'Katherine Johnson', 'Michael Williams', 'Joseph Turner', 'Peter Potter', 'Ryan Kim', 'Janice Yoder', 'Carolyn Webb', 'Elizabeth Bush', 'Jaime Edwards', 'Bethany Smith', 'Wanda Grimes', 'Karina Allison', 'Timothy Smith', 'Jason Harris', 'Thomas Smith', 'John Whitaker', 'Kimberly Brown ', 'Barbara Miller', 'Madeline Lopez', 'Carlos Fischer', 'Amy Collins', 'Abigail White', 'Joanne Strickland', 'Maria Hernandez', 'Sandra Mcdowell', 'Kristin Krause', 'Alicia Reese', 'Isaac Holt', 'Jonathan Garza', 'Phillip Smith', 'Amanda Vazquez', 'Jaime Holland', 'Tina Rhodes', 'John Wells', 'Lindsay Dougherty', 'Caitlyn Vega', 'Kevin Campbell', 'Michael Everett', 'Christian Martinez', 'Chad Rivera', 'Amanda Ferrell', 'Natasha Murphy', 'Kathleen Cook', 'Steven Lewis Jr.', 'Raymond Hardy', 'Michael Hill', 'Mary Summers', 'Barbara Cardenas', 'Angela Garcia ', 'Ronnie Craig', 'Chad Miller', 'Margaret Perez', 'Michael Rodriguez', 'Preston Davis', 'Michael Reed', 'Matthew Ball', 'Larry Robinson', 'Kyle Gonzalez', 'Sarah Atkinson', 'William Foster PhD', 'Michael James', 'Michael Strong', 'Kenneth Moore', 'Brittney Coleman', 'Jacob Stein', 'Jason Rodgers', 'Jose Newton', 'John Wheeler', 'April Ellis', 'Caleb Young', 'Derrick Alexander', 'Jasmine Li', 'Michael Higgins', 'Joel French', 'Sheri Taylor', 'Vanessa Wagner', 'Amanda Ramirez', 'Susan Gates', 'Jason Lawrence', 'Jonathan Alvarez', 'Joshua Graham', 'Jeffery Gomez', 'Sara Hughes', 'Sandy Johns', 'Melissa Carter', 'Emma Foley', 'Jennifer Harris', 'Gloria Wilson', 'Angela Daniels', 'Marcus Morgan', 'Joanna Allen', 'Lisa Kennedy', 'Joseph Stewart', 'Lindsey Thompson', 'Lori Dickson', 'Jeremy Edwards', 'Joseph Burgess', 'Antonio Kirk', 'Renee Mcdonald', 'Kelli Barnes', 'Lucas Williams Jr.', 'Kathleen Barr', 'Nancy Silva', 'Rachel Murphy', 'Rhonda Rodriguez', 'Tammy Torres', 'Jennifer White', 'Carrie Stewart', 'Karen Rogers', 'Kimberly Page', 'Catherine Mendoza', 'Stacy Wells', 'Crystal Smith', 'Ernest Lawrence', 'Sharon Nguyen', 'Mary Coffey', 'Kimberly Pruitt', 'Richard Mcdonald', 'Gregory Taylor', 'Joseph Ho', 'Anna Smith', 'Daniel Best', 'Terri Johnston', 'Katherine Harrison', 'Megan Carson', 'Stephanie Wilson', 'Samantha Johnson', 'Andrew Merritt', 'Susan Simon', 'Maria Shields', 'Samuel Casey', 'Robert Wood', 'Jonathan Mueller', 'Diane Miller', 'Brett Arnold', 'Brian Williams', 'Shawn Hayden', 'Emily Gomez', 'Kerri Berger', 'Laura Webster', 'Elizabeth Aguirre', 'Victoria Bailey', 'Monica Hampton', 'Catherine Lee', 'Cheyenne Hernandez', 'Jonathan Sullivan', 'Deborah Higgins ', 'Steven Jackson', 'Cristian Webster', 'Audrey Fry', 'Michael Carroll', 'Raymond Hawkins', 'Christopher Wilson', 'Glenda Fletcher', 'Jennifer Hamilton', 'Shannon Williams', 'Lori Moore', 'William Hubbard', 'Bradley Johnson', 'John Brooks', 'Stephanie Contreras', 'Kristen Gonzalez', 'Kari Holloway', 'Kimberly Cabrera', 'Katie Weaver', 'April Reyes', 'Derek Weeks', 'John Reese', 'Joseph Anthony', 'Donna Howard', 'Dawn Bell', 'Rebecca Tanner', 'Desiree Kidd', 'Carolyn Jackson']

In [141]:
#create new column with no prefix/suffix in names
clean_names = []

for name in fixed_names:
    if len(name.split()) >= 3:
        clean_names.append(name)
len(clean_names)

425

In [142]:
print(clean_names)

['Joseph Morales III', 'Mrs. Elizabeth Espinoza ', 'Mrs. Lisa Becker', 'Xavier Bell II', 'Mrs. Cindy Brown', 'Mrs. Catherine Williams ', 'Michael Moreno PhD', 'Mrs. Paula Lee', 'Mrs. Jessica Dunn', 'David Miller Jr.', 'Mrs. Marcia Jones PhD', 'Reginald Garcia IV', 'Kevin Brown IV', 'Mrs. Kathleen Reed', 'Mrs. Dawn Olson ', 'William Washington Jr.', 'Darlene Thomas PhD', 'Juan Bryant II', 'Kenneth Paul Jr.', 'Scott Rivers III', 'Mark Myers Jr.', 'Mrs. Maria Smith ', 'Todd Greene PhD', 'Mrs. Lisa Rowland', 'Mrs. Alicia Kelly ', 'Michael Norton Jr.', 'Sean Pena Jr.', 'Mrs. Jill Walker', 'Cody Mueller Jr.', 'Mathew White Jr.', 'Steven Snyder PhD', 'Jessica Warner PhD', 'Mrs. Rebecca Martin ', 'Jason Daugherty Jr.', 'Mrs. Natalie Holder ', 'Mrs. Susan Chase ', 'Leonard Webster II', 'David Taylor PhD', 'Terri Quinn PhD', 'Mrs. Gina Anderson', 'Michael Stein Jr.', 'Mrs. Mikayla White', 'Alexandra Hood PhD', 'Ryan Phillips Jr.', 'Mrs. Crystal Perez', 'Mario Wheeler PhD', 'Mrs. Alexandra Taylor', 'Mrs. Amy Walker ', 'Mrs. Elizabeth Mitchell', 'Allen Snyder Jr.', 'Calvin Williams Jr.', 'Ronald Torres Jr.', 'Richard Williams PhD', 'Michael Baker PhD', 'Mrs. Janice Dixon', 'Gabriel Smith III', 'Ronald Mayer PhD', 'Brian Pitts Jr.', 'Bruce Thompson II', 'Jeremy Sanders II', 'Mrs. Michelle Butler', 'Mrs. Jennifer Martin ', 'Mrs. Mary Hardy', 'Jennifer Smith PhD', 'Mrs. Kara Rodriguez ', 'Austin Johnson II', 'Mrs. Wendy Thomas', 'Bryan Conway Jr.', 'Mrs. Casey Hayes', 'Mrs. Lori Johnson', 'Mrs. Laurie Brown', 'Ronald Moore II', 'Alexander Garcia PhD', 'Mrs. Paige Hall', 'Mrs. Ashley Porter ', 'Joshua Garrison PhD', 'Mrs. Leslie Mathews', 'Jennifer Long PhD', 'Robert Garrison IV', 'William Gonzalez Jr.', 'Brian Matthews Jr.', 'Mrs. Jacqueline Rose', 'Mrs. Angela Gray', 'Mrs. Tara Carpenter', 'Mrs. Catherine Armstrong', 'Eric Richards Jr.', 'Mrs. Angela Martinez', 'Mrs. Laura Malone ', 'Kenneth Munoz Jr.', 'Jon Delgado Jr.', 'Mrs. Anna Dickerson', 'Mrs. Cynthia Martinez ', 'Mrs. Stephanie Stone', 'Jordan Brewer PhD', 'Mrs. Veronica Neal', 'Andrew English Jr.', 'Mrs. Jennifer Tucker ', 'Mrs. Jamie Bond', 'Raymond Cox Jr.', 'Jeffrey Mcclain Jr.', 'Melissa Rodriguez PhD', 'Mrs. Andrea Wilson', 'Jonathan Woods PhD', 'Brian Poole V', 'Jeffrey Kim II', 'April Hansen PhD', 'Melissa Allen PhD', 'Mrs. Sophia Harper', 'Mrs. Natasha White', 'Matthew Alexander Jr.', 'Mrs. Theresa Roberts', 'Kevin Reynolds Jr.', 'Jacob Skinner Jr.', 'Haley Jordan PhD', 'Dennis Gibson Jr.', 'Mrs. Sherry Flores ', 'Jimmy Shea Jr.', 'Mrs. Jasmine Schroeder', 'Mrs. Danielle Jones', 'Mrs. Theresa Bauer', 'James Reed Jr.', 'Mrs. Gina Williams', 'Mrs. Bonnie Boyd PhD', 'Eric Lambert PhD', 'Mrs. Michelle Dickerson ', 'Mrs. Jessica Hebert', 'Mrs. Whitney Scott', 'Miranda Thompson PhD', 'Mrs. Tanya Odom', 'Jeffery Baker Jr.', 'Mrs. Melissa Medina', 'Mrs. Nicole Vazquez', 'Derrick Hughes III', 'Joshua Rivera Jr.', 'Mrs. Renee Thomas ', 'Mrs. Christina Horne', 'Mrs. Deborah Walters PhD', 'Mrs. Anita Lee', 'Timothy Guzman Jr.', 'Mrs. Kelly Hall', 'Mrs. Anna Everett ', 'Mrs. Robin Lopez ', 'Mrs. Molly Lopez ', 'Jose Huffman PhD', 'Mrs. Robin Hughes', 'Mrs. Tracy Williams', 'Lonnie Allen II', 'Tyrone Clark III', 'Mrs. Megan Kaufman ', 'Mrs. Whitney Figueroa', 'Jeffrey Nelson Jr.', 'Michael Mann II', 'Mrs. Karina Perry', 'Jessica Sanchez PhD', 'Joseph Ellis PhD', 'Mrs. Heather Gregory', 'Nathan Welch PhD', 'David Johnson Jr.', 'Timothy Chavez Jr.', 'Mrs. Brooke Henry ', 'Brian Powell III', 'Logan Oconnell PhD', 'Lance Rangel Jr.', 'Mrs. Brooke Rodgers', 'Mrs. Brittany Duncan ', 'Mrs. Jennifer Edwards ', 'William Cook PhD', 'Robert Sanders PhD', 'Noah Herrera Jr.', 'Mrs. Brenda Bishop ', 'Mrs. Sheila Wagner', 'Mrs. Kathleen Johnson ', 'Paul Jensen PhD', 'Mrs. Susan Klein', 'Mrs. Leslie Esparza', 'Mrs. Jacqueline Simpson', 'Mrs. Tammy Crane', 'Mrs. Nancy Landry', 'Mrs. Amanda Cook', 'Mrs. Lauren Lewis', 'Eric Johnson Jr.', 'Kelly Webb PhD', 'Mrs. Taylor Martin', 'Victor Chavez II', 'Mrs. Lauren Campbell', 'Richard Ellis Jr.', 'Mrs. Brooke Campbell', 'Charles Goodman Jr.', 'Mrs. Kimberly Key ', 'Patrick Barker PhD', 'Michael Singh Jr.', 'Jonathan Smith Jr.', 'Allen Morris Jr.', 'Aaron Solis Jr.', 'Mrs. Victoria Cochran', 'Daniel Mckinney Jr.', 'Mrs. Angelica Hall', 'Christopher Petty Jr.', 'Mrs. Nicole Duran', 'Michael Garcia Jr.', 'Mrs. Bethany Fisher PhD', 'Charles Short II', 'Kimberly Jacobson PhD', 'Daniel Fitzpatrick PhD', 'Derek Barker Jr.', 'Mrs. Renee Gordon', 'Mrs. Amanda Martin', 'Mrs. Katie Weber ', 'Mrs. Pamela Garcia', 'Karen Harris PhD', 'Mrs. Amanda Herring', 'Mrs. Sheena Bailey ', 'Zachary Garrett III', 'Thomas Harrison Jr.', 'Andrew Mitchell V', 'Mrs. Amy Cain', 'Aaron Davis Jr.', 'Mrs. Pam Lewis ', 'Brian Bailey Jr.', 'Mrs. Carla Humphrey', 'Yvonne Robinson PhD', 'Christopher Simmons PhD', 'Jeremiah Morris IV', 'David Morales Jr.', 'Larry Chandler Jr.', 'Ronald Matthews PhD', 'James Clark II', 'Cameron Roman Jr.', 'Christopher Smith Jr.', 'Mrs. Lori Rogers ', 'Matthew Sawyer PhD', 'Mike Harris PhD', 'Mrs. Christina Mitchell ', 'Christina Alvarez PhD', 'Todd Grant Jr.', 'Mrs. Veronica Sherman', 'Mrs. Jennifer Rivera', 'Mrs. Wendy Hayes', 'Mrs. Michelle Patterson', 'Mrs. Jennifer Craig', 'Mrs. Amanda Rose', 'Mrs. Kathleen Cook', 'Kevin Andrews PhD', 'Kenneth Avila Jr.', 'Jason Lopez Jr.', 'Mrs. Carol White', 'Mrs. Sabrina Murillo ', 'Mrs. Brenda Johnson ', 'Billy Franco PhD', 'Alexander Chang PhD', 'Mrs. Cynthia Lopez', 'Devin Sharp PhD', 'Chelsea Sullivan PhD', 'Dwayne Mathis Jr.', 'Cheryl Gay PhD', 'Colton Collins II', 'Chris Palmer III', 'Sean Coleman PhD', 'Tyler Randall Jr.', 'Mrs. Denise Vasquez', 'Joseph Morgan IV', 'Carlos Adkins Jr.', 'Mrs. Melissa Vasquez', 'Mark Livingston Jr.', 'Mrs. Kaitlin Oconnor ', 'Mrs. Margaret Watson', 'Mrs. Nancy Blair', 'Mrs. Brittany Ford ', 'Michael Williams III', 'Mrs. Wendy Gomez ', 'Mrs. Katherine Jones', 'Mrs. Theresa Winters', 'Eric Evans III', 'Mrs. Jordan White ', 'Christopher Thornton Jr.', 'Mrs. Julie Powers', 'Adam Hayes III', 'Mrs. Angela Floyd', 'Brittany Sanchez PhD', 'Mrs. Alexandra Hamilton', 'Michael Moore Jr.', 'Mrs. Sharon Rose', 'Joseph Hudson II', 'William Brooks Jr.', 'Mrs. Melissa Ingram ', 'Mrs. Melanie Martinez PhD', 'Daniel Welch II', 'Roger Horton Jr.', 'Mrs. Angela Williams', 'Cory Marshall II', 'Mrs. Megan Clark ', 'Joshua Thompson Jr.', 'Tina White PhD', 'Mrs. Susan Mccormick', 'Mrs. Kimberly Floyd ', 'Mrs. Samantha Jackson', 'Roger Forbes PhD', 'Mrs. Kimberly Brandt', 'Mrs. Dana Hammond ', 'Mrs. Kelsey Marshall', 'Jon Flores II', 'Mrs. Lisa Lyons ', 'Philip Jones Jr.', 'Greg Joyce Jr.', 'Mrs. Mary Duarte ', 'Mrs. Lisa Baker', 'Thomas Frye Jr.', 'Patrick Mcdaniel PhD', 'Robert Edwards PhD', 'Cynthia Mclaughlin PhD', 'Mrs. Heather Price', 'Joseph Marquez Jr.', 'Mrs. Barbara Sanchez', 'Adam Munoz PhD', 'Robert Smith Jr.', 'David Beck Jr.', 'Mrs. Joyce Cunningham', 'Mrs. Tara Lee', 'Mrs. Ashley Martin', 'Christopher Moore PhD', 'Gail Page PhD', 'Mrs. Karen Wright ', 'Ryan Gomez II', 'Mrs. Rachel Hensley', 'Mrs. Cynthia Lawrence', 'Erik Smith Jr.', 'Omar Thompson Jr.', 'Leonard Roberts Jr.', 'Duane Li Jr.', 'Mrs. Ashley Floyd', 'Matthew Higgins PhD', 'Christian Hurst PhD', 'Mrs. Rachel Newman ', 'Mrs. Amy Bradford ', 'Mrs. Melissa Ramirez', 'Richard Lucero Jr.', 'Elizabeth Holder PhD', 'Mrs. Shannon Gonzalez ', 'Seth Medina Jr.', 'Mrs. Lindsey White', 'Mrs. Jennifer Chavez ', 'Mrs. Lisa Vargas ', 'Mrs. Jennifer Kelly', 'Richard Curry PhD', 'Mrs. Anna Perez', 'Anthony Carlson Jr.', 'Mrs. Rhonda Bradley', 'Mrs. Tamara Burns', 'Mrs. Brittany Boone ', 'Debra Torres PhD', 'Edward Dudley II', 'Matthew Lewis Jr.', 'Jacob Perez PhD', 'Isaac Smith PhD', 'Christopher Bowers Jr.', 'Wendy Arroyo PhD', 'Mrs. Lisa Guerrero', 'Timothy Hughes Jr.', 'Kevin Hoover IV', 'Mrs. Laurie Hamilton', 'David Butler Jr.', 'Mrs. Adrienne Evans ', 'Michael Wilson Jr.', 'Mrs. Carolyn Cole', 'Mrs. Lisa Doyle', 'Elizabeth Robinson PhD', 'George Hess Jr.', 'Courtney Cox PhD', 'Kevin Briggs Jr.', 'Mrs. Tabitha Coleman', 'Joseph Matthews III', 'Mrs. Brenda Henderson ', 'Dylan Bailey Jr.', 'Anthony Woods Jr.', 'Michael Harris Jr.', 'Daniel Diaz Jr.', 'Mrs. April Thornton', 'Cristian Williams PhD', 'Mrs. Amanda Harris ', 'Taylor Thompson Jr.', 'Daniel Robinson Jr.', 'Melissa Barnett PhD', 'Mrs. Amber Garner ', 'Mrs. Alicia Sanford', 'Mrs. Laura Sexton', 'Ronald Phelps Jr.', 'Mrs. Jessica Flynn', 'Mrs. Elizabeth Jones', 'Michael Miller PhD', 'Mrs. Sharon Kelley', 'Jonathan Reid II', 'Mrs. Taylor Castillo', 'Joshua Smith Jr.', 'Joseph Herrera III', 'Mrs. Jordan Turner', 'Andrew Walsh PhD', 'Mrs. Lauren Collins', 'Mrs. Chelsea Roberts ', 'Vicki Santos PhD', 'Tony Robertson II', 'James Fowler III', 'Mrs. Brittany Perry ', 'William Wright II', 'Thomas Carrillo II', 'Matthew Bennett Jr.', 'Mrs. Carla Lawson', 'Mrs. Allison Robinson', 'Mrs. Amber Hall', 'Mark Lucas IV', 'Keith Newman Jr.', 'Matthew Mitchell III', 'Harold Parker PhD', 'Colin Schultz II', 'Terry Scott Jr.', 'Mrs. Kristen Gonzalez', 'Mrs. Alice Warren', 'David Coffey PhD', 'Mrs. Pam Wolf ', 'Mrs. Samantha Glover', 'Mrs. Amber Gonzalez', 'Jason Patel Jr.', 'Mrs. Brittney Schultz ', 'Steven Lewis Jr.', 'William Foster PhD', 'Lucas Williams Jr.']

In [149]:
# save cleaned file
df.head(-25)
df.to_csv('Resources/cleaned_students_complete.csv', index=False)